using OryxDomain.Models.Enums;
using System;

namespace OryxDomain.Models.Oryx
{
    public class CV5
    {
        public string Cv5emissor { get; set; }
        public string Cv5tipo { get; set; }
        public string Cv5doc { get; set; }
        public bool Cv5emispro { get; set; }
        public bool Cv5tamanho { get; set; }
        public bool Cv5ean { get; set; }
        public bool Cv5cupom { get; set; }
        public bool Cv5online { get; set; }
        public string Cv5emisnom { get; set; }
        public string Cv5emisest { get; set; }
        public string Cv5ecf { get; set; }
        public string Cv5atende { get; set; }
        public string Cv5totaliz { get; set; }
        public string Cv5usuario { get; set; }
        public DateTime Cv5emissao { get; set; }
        public string IssueDate
        {
            get
            {
                return this.Cv5emissao.ToString("dd/MM/yyyy HH:mm");
            }
        }
        public DateTime Cv5dhsaida { get; set; }
        public string Cv5cliente { get; set; }
        public string Cv5repres { get; set; }
        public string Cv5repnom { get; set; }
        public string Cv5pedido { get; set; }
        public string Cv5embarq { get; set; }
        public string Cv5pedcom { get; set; }
        public string Cv5docrec { get; set; }
        public string Cv5docmov { get; set; }
        public string Cv5transp { get; set; }
        public string Cv5redesp { get; set; }
        public string Cv5pedrep { get; set; }
        public string Cv5conpgto { get; set; }
        public string Cv5centro { get; set; }
        public bool Cv5editar { get; set; }
        public string Cv5conpnom { get; set; }
        public string Cv5lista { get; set; }
        public decimal Cv5limdesc { get; set; }
        public decimal Cv5limdesp { get; set; }
        public int Cv5limdias { get; set; }
        public int Cv5limpraz { get; set; }
        public string Cv5nomlis { get; set; }
        public string Cv5opercom { get; set; }
        public string Cv5operdes { get; set; }
        public GoodsFlowType Cv5entsai { get; set; }
        public bool Cv5consig { get; set; }
        public string Cv5hisemi { get; set; }
        public string Cv5hisliq { get; set; }
        public string Cv5cst { get; set; }
        public string Cv5titulo { get; set; }
        public string Cv5titnom { get; set; }
        public string Cv5bcopor { get; set; }
        public string Cv5nompor { get; set; }
        public decimal Cv5comis { get; set; }
        public decimal Cv5descon { get; set; }
        public decimal Cv5desconv { get; set; }
        public decimal Cv5despon { get; set; }
        public int Cv5desdias { get; set; }
        public FreightType Cv5frete { get; set; }
        public bool Cv5pronta { get; set; }
        public decimal Cv5qtdevol { get; set; }
        public string Cv5espevol { get; set; }
        public string Cv5marcvol { get; set; }
        public string Cv5numevol { get; set; }
        public decimal Cv5pesobru { get; set; }
        public decimal Cv5pesoliq { get; set; }
        public string Cv5trplaca { get; set; }
        public string Cv5trplauf { get; set; }
        public decimal Cv5aliqicm { get; set; }
        public decimal Cv5baseicm { get; set; }
        public decimal Cv5valicm { get; set; }
        public decimal Cv5baseise { get; set; }
        public decimal Cv5baseout { get; set; }
        public decimal Cv5baseicp { get; set; }
        public decimal Cv5baseisp { get; set; }
        public decimal Cv5baseoup { get; set; }
        public decimal Cv5baseipi { get; set; }
        public string Cv5observ { get; set; }
        public decimal Cv5basesup { get; set; }
        public decimal Cv5aliqsub { get; set; }
        public decimal Cv5basesub { get; set; }
        public decimal Cv5valsub { get; set; }
        public decimal Cv5totalpr { get; set; }
        public decimal Cv5vlfrete { get; set; }
        public decimal Cv5seguro { get; set; }
        public decimal Cv5outras { get; set; }
        public decimal Cv5ipi { get; set; }
        public decimal Cv5totalnf { get; set; }
        public string Cv5modelo { get; set; }
        public string Cv5serie { get; set; }
        public string Cv5subser { get; set; }
        public string Cv5cfop { get; set; }
        public string Cv5cfopnom { get; set; }
        public string Cv5clinome { get; set; }
        public string Cv5endcli { get; set; }
        public string Cv5cep { get; set; }
        public string Cv5insest { get; set; }
        public string Cv5fone { get; set; }
        public string Cv5nomeloc { get; set; }
        public string Cv5estado { get; set; }
        public string Cv5trnome { get; set; }
        public string Cv5trcnpj { get; set; }
        public string Cv5trender { get; set; }
        public string Cv5trestad { get; set; }
        public string Cv5trlocal { get; set; }
        public string Cv5trinscr { get; set; }
        public SalesItemType Cv5itemfab { get; set; }
        public bool Cv5cnpj { get; set; }
        public bool Cv5cic { get; set; }
        public bool Cv5emitido { get; set; }
        public bool Cv5impres { get; set; }
        public string Cv5flag1 { get; set; }
        public string Cv5contad { get; set; }
        public string Cv5contac { get; set; }
        public string Cv5situa { get; set; }
        public decimal Cv5credsim { get; set; }
        public string Cv5nfechav { get; set; }
        public string Cv5cstipi { get; set; }
        public string Cv5cstpis { get; set; }
        public decimal Cv5basepis { get; set; }
        public decimal Cv5aliqpis { get; set; }
        public string Cv5cstcof { get; set; }
        public decimal Cv5basecof { get; set; }
        public decimal Cv5aliqcof { get; set; }
        public decimal Cv5baseiss { get; set; }
        public decimal Cv5aliqiss { get; set; }
        public string Cv5codiss { get; set; }
        public string Cv5ndi { get; set; }
        public DateTime Cv5ddi { get; set; }
        public string Cv5locdes { get; set; }
        public string Cv5ufdes { get; set; }
        public DateTime Cv5ddes { get; set; }
        public string Cv5codexp { get; set; }
        public string Cv5nadicao { get; set; }
        public string Cv5seqadic { get; set; }
        public string Cv5fabric { get; set; }
        public decimal Cv5descad { get; set; }
        public decimal Cv5baseii { get; set; }
        public decimal Cv5impimp { get; set; }
        public decimal Cv5despad { get; set; }
        public decimal Cv5iofimp { get; set; }
        public string Cv5ufemb { get; set; }
        public string Cv5locemb { get; set; }
        public string Cv5endentr { get; set; }
        public string Cv5ufentr { get; set; }
        public string Cv5desentr { get; set; }
        public string Cv5cepentr { get; set; }
        public string Cv5digval { get; set; }
        public string Cv5nprot { get; set; }
        public DateTime Cv5dhrec { get; set; }
        public string Cv5xml { get; set; }
        public decimal Cv5titulo1 { get; set; }
        public decimal Cv5titulo2 { get; set; }
        public decimal Cv5titulo3 { get; set; }
        public string Cv5baicli { get; set; }
        public string Cv5numcli { get; set; }
        public string Cv5local { get; set; }
        public string Cv5compl { get; set; }
        public string Cv5reclote { get; set; }
        public string Cv5pais { get; set; }
        public string Cv5email { get; set; }
        public string Cv5origem { get; set; }
        public bool Cv5naocont { get; set; }
        public string Cv5enqipi { get; set; }
        public decimal Cv5aliqipi { get; set; }
        public decimal Cv5pisimp { get; set; }
        public decimal Cv5cofimp { get; set; }
        public string Cv5numdraw { get; set; }
        public string Cv5tipoda { get; set; }
        public string Cv5ufda { get; set; }
        public string Cv5numda { get; set; }
        public string Cv5autda { get; set; }
        public decimal Cv5valorda { get; set; }
        public DateTime Cv5vctoda { get; set; }
        public DateTime Cv5pgtoda { get; set; }
        public string Cv5indproc { get; set; }
        public string Cv5numproc { get; set; }
        public bool Cv5ajuste { get; set; }
        public bool Cv5credpis { get; set; }
        public bool Cv5credcof { get; set; }
        public bool Cv5credicm { get; set; }
        public string Cv5numorig { get; set; }
        public decimal Cv5vlrserv { get; set; }
        public string Cv5tipolig { get; set; }
        public string Cv5tensao { get; set; }
        public string Cv5codcons { get; set; }
        public string Cv5docdev { get; set; }
        public string Cv5contige { get; set; }
        public string Cv5regdpec { get; set; }
        public string Cv5estadoc { get; set; }
        public string Cv5destinc { get; set; }
        public decimal Cv5vnfc { get; set; }
        public decimal Cv5vicmsc { get; set; }
        public decimal Cv5tottrib { get; set; }
        public bool Cv5tottri1 { get; set; }
        public int Cv5tpviatr { get; set; }
        public decimal Cv5vafrmm { get; set; }
        public bool Cv5tpinter { get; set; }
        public string Cv5cnpjter { get; set; }
        public decimal Cv5pdif { get; set; }
        public decimal Cv5fcpdest { get; set; }
        public decimal Cv5icmdest { get; set; }
        public decimal Cv5icmreme { get; set; }
        public decimal Cv5descfat { get; set; }
        public string Cv5nprocan { get; set; }
        public string Cv5nproinu { get; set; }
        public string Cv5docconf { get; set; }
        public decimal Cv5cambio { get; set; }
        public string Cv5cbenef { get; set; }
        public bool Cv5peca { get; set; }
        public decimal Cv5vfcpst { get; set; }
        public string Cv5caixa { get; set; }
        public string Autenticacao { get; set; }
    }
}
