//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OryxDomain.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível encontrar o campo {0} no dicionário de dados..
        /// </summary>
        internal static string Message_DictionaryColumnNotFound {
            get {
                return ResourceManager.GetString("Message_DictionaryColumnNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível encontrar a conexão com o banco de dados..
        /// </summary>
        internal static string Message_ErrorInGetConnectionString {
            get {
                return ResourceManager.GetString("Message_ErrorInGetConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necessário no mínimo um caracter especial..
        /// </summary>
        internal static string Message_EspecialCaracterValidation {
            get {
                return ResourceManager.GetString("Message_EspecialCaracterValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necessário no mínimo uma letra minúscula..
        /// </summary>
        internal static string Message_PassLowerCaseValidation {
            get {
                return ResourceManager.GetString("Message_PassLowerCaseValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necessário no mínimo um número..
        /// </summary>
        internal static string Message_PassNumberValidation {
            get {
                return ResourceManager.GetString("Message_PassNumberValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necessário no mínimo 8 dígitos..
        /// </summary>
        internal static string Message_PassSizeValidation {
            get {
                return ResourceManager.GetString("Message_PassSizeValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necessário no mínimo uma letra maiúscula..
        /// </summary>
        internal static string Message_PassUpperCaseValidation {
            get {
                return ResourceManager.GetString("Message_PassUpperCaseValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha não cumpre os requisitos mínimos de segurança..
        /// </summary>
        internal static string Message_PasswordInvalid {
            get {
                return ResourceManager.GetString("Message_PasswordInvalid", resourceCulture);
            }
        }
    }
}
