
CREATE TABLE LXD (
  LXDPADRAO char(1) DEFAULT NULL,
  LXDLISTA CHAR(3) DEFAULT NULL,
  LXDEAN decimal(1,0) DEFAULT 0,
  LXDINTESHO decimal(1,0) DEFAULT 0,
  LXDTIPINSH decimal(1,0) DEFAULT 0,
  LXDCLIENTE char(14) DEFAULT '',
  LXDCONPGTO char(3) DEFAULT '',
  LXDTITULO char(3) DEFAULT '',
  LXDROMANF decimal(1,0) DEFAULT 0,
  LXDMANTER decimal(1,0) DEFAULT 0,
  LXDDEVANO decimal(1,0) DEFAULT 0,
  LXDDEVDIAS decimal(4,0) DEFAULT 0,
  LXDOBRCLI decimal(1,0) DEFAULT 0,
  LXDRFID decimal(1,0) DEFAULT 0,
  LXDNFCE decimal(1,0) DEFAULT 0,
  LXDCONSIG decimal(1,0) DEFAULT 0,
  LXDNF decimal(1,0) DEFAULT 0,
  LXDROMANEI decimal(1,0) DEFAULT 0,
  LXDQTDE decimal(1,0) DEFAULT 0,
  LXDMULTROM decimal(1,0) DEFAULT 0,
  LXDTITULO1 CHAR(3) DEFAULT '',
  LXDTITULO2 CHAR(3) DEFAULT '',
  LXDTITULO3 CHAR(3) DEFAULT '',
  LXDTITULOD CHAR(3) DEFAULT '',
  LXDDOCVEN1 CHAR(3) DEFAULT '',
  LXDDOCVEN2 CHAR(3) DEFAULT '',
  LXDDOCVEN3 CHAR(3) DEFAULT '',
  LXDDOCVEN4 CHAR(3) DEFAULT '',
  LXDDOCVEN5 CHAR(3) DEFAULT '',
  LXDDOCDEV1 CHAR(3) DEFAULT '',
  LXDDOCDEV2 CHAR(3) DEFAULT '',
  LXDDOCDEV3 CHAR(3) DEFAULT '',
  LXDDOCDEV4 CHAR(3) DEFAULT '',
  LXDDEVVEN DECIMAL(1,0) DEFAULT 0,
  LXDCONSNF DECIMAL(1,0) DEFAULT 0,
  LXDULTGUIA DECIMAL(1,0) DEFAULT 0,
  LXDMOTIDEV CHAR(2) DEFAULT ' ',
  LXDENTRDEV DECIMAL(1,0) DEFAULT 0,
  LXDDOCENT1 CHAR(3) DEFAULT '',
  LXDDOCENT2 CHAR(3) DEFAULT '',
  LXDDESCDEV DECIMAL(1,0) DEFAULT 0,
  PRIMARY KEY (LXDPADRAO)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO DC0 (DC0ARQUIVO,DC0NOME,DC0ACESSO,DC0NAOIMP,DC0NAOEXP,DC0CONEXAO,DC0TIPO)  values ('LXD','Parâmetros PDV',0,0,0,1,0);

Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('LXDPADRAO','Padrão de PDV','LXD','','','','C',1,0,0,0,0,1,'Campo exclusivamente para chave','',0,'');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('LXDLISTA', 'Lista Padrão', 'LXD', 'CV6', 'CV6LISTA', '', 'C', 3, 0, 0, 1, 0, 1, 'Lista de Preço Padrão', 'CV6', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('LXDEAN', 'Somente Leitura EAN', 'LXD', '', '', '', 'N', 1, 0, 0, 0, 1, 0, 'Utilizar somente leitura de peças por código de barras', '', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('LXDINTESHO', 'Integração shopping', 'LXD', '', '', '', 'N', 1, 0, 0, 0, 1, 0, 'Habilita integração de vendas para o shopping', '', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('LXDCLIENTE', 'Cliente Padrão', 'LXD', 'CF1', 'CF1CLIENTE', '', 'C', 14, 0, 1, 0, 1, 0, 'Cliente padrão utilizado no PDV', 'CF1', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('LXDCONPGTO', 'Condição de Pagamento', 'LXD', 'VD4', 'VD4CONPGTO', '', 'C', 3, 0, 0, 1, 0, 0, 'Condição de Pagamento padrão', 'VD4', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('LXDTITULO', 'Tipo de Título Padrão', 'LXD', 'CV2', 'CV2TITULO', '', 'C', 3, 0, 0, 0, 1, 0, 'Tipo padrão de Título.', 'CV2', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('LXDROMANF', 'Romaneio + NF', 'LXD', '', '', '', 'N', 1, 0, 0, 0, 1, 0, 'Quando essa opção estiver ativa, toda venda (NF-e, NFC-e e Consignado) será emitido o romaneio', '', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('LXDMANTER', 'Manter Item no Pedido', 'LXD', '', '', '', 'N', 1, 0, 0, 0, 1, 0, 'Mantem ítem no pedido como pendente, ou seja, não serão cancelados os itens devolvidos.', '', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('LXDDEVANO', 'Apenas no ano', 'LXD', '', '', '', 'N', 1, 0, 0, 0, 1, 0, 'Bloqueia devoluções para vendas dentro do ano.', '', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('LXDDEVDIAS', 'Em até dias', 'LXD', '', '', '', 'N', 4, 0, 0, 0, 1, 0, 'Permite devolução de peças até a quantidade de dias informado.', '', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('LXDOBRCLI', 'Exigir cliente 1°', 'LXD', '', '', '', 'N', 1, 0, 0, 0, 1, 0, 'Permite exigir o cliente antes de adicionar os produtos no carrinho.', '', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('LXDRFID', 'Habilitar RFID', 'LXD', '', '', '', 'N', 1, 0, 0, 0, 1, 0, 'Habilitar leitura RFID no sistema', '', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('LXDCONSIG', 'Habilitar Consignado', 'LXD', '', '', '', 'N', 1, 0, 0, 0, 1, 0, 'Habilitar emissão de consignado', '', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('LXDNFCE', 'Habilitar NFCe', 'LXD', '', '', '', 'N', 1, 0, 0, 0, 1, 0, 'Habilitar emissão de Cupom Fiscal Eletronico', '', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('LXDNF', 'Habilitar NF', 'LXD', '', '', '', 'N', 1, 0, 0, 0, 1, 0, 'Habilitar emissão de Notas Fiscais Eletrônicas', '', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('LXDROMANEI', 'Habilitar Romaneio', 'LXD', '', '', '', 'N', 1, 0, 0, 0, 1, 0, 'Habilitar emissão de Romaneio', '', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('LXDQTDE', 'Exige quantidade', 'LXD', '', '', '', 'N', 1, 0, 0, 0, 1, 0, 'Exige digitação da quantidade na tela de vendas do PDV', '', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('LXDMULTROM', 'Múltiplos romaneios', 'LXD', '', '', '', 'N', 1, 0, 0, 0, 1, 0, 'Habilita múltiplos romaneios', '', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('LXDTIPINSH', 'Tipo int. Shop.', 'LXD', '', '', '', 'N', 1, 0, 0, 0, 1, 0, 'Define o tipo de integração com shopping', '', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('LXDTITULO1', 'Meio de Pagamento 1', 'LXD', 'CV2', 'CV2TITULO', '', 'C', 3, 0, 0, 0, 1, 0, 'Opção de pagamento 1', 'CV2', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('LXDTITULO2', 'Meio de Pagamento 2', 'LXD', 'CV2', 'CV2TITULO', '', 'C', 3, 0, 0, 0, 1, 0, 'Opção de pagamento 2', 'CV2', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('LXDTITULO3', 'Meio de Pagamento 3', 'LXD', 'CV2', 'CV2TITULO', '', 'C', 3, 0, 0, 0, 1, 0, 'Opção de pagamento 3', 'CV2', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('LXDTITULOD', 'Titulo troca/dev.', 'LXD', 'CV2', 'CV2TITULO', '', 'C', 3, 0, 0, 0, 1, 0, 'Meio de pagamento para devolução/troca', 'CV2', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('LXDDOCVEN1', 'Doc. ven. romaneio', 'LXD', 'CV1', 'CV1DOCFIS', '', 'C', 3, 0, 0, 1, 0, 1, 'Documento fiscal de venda para romaneios', 'CV1', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('LXDDOCVEN2', 'Doc. ven. cons rom', 'LXD', 'CV1', 'CV1DOCFIS', '', 'C', 3, 0, 0, 1, 0, 1, 'Documento fiscal de venda para consignados em romanio', 'CV1', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('LXDDOCVEN3', 'Doc. ven. CF', 'LXD', 'CV1', 'CV1DOCFIS', '', 'C', 3, 0, 0, 1, 0, 1, 'Documento fiscal de venda para cupom fiscal', 'CV1', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('LXDDOCVEN4', 'Doc. ven. NF', 'LXD', 'CV1', 'CV1DOCFIS', '', 'C', 3, 0, 0, 1, 0, 1, 'Documento fiscal de venda para nota fiscal', 'CV1', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('LXDDOCVEN5', 'Doc. ven. cons. NF', 'LXD', 'CV1', 'CV1DOCFIS', '', 'C', 3, 0, 0, 1, 0, 1, 'Documento fiscal de venda para consignados em nota fiscal', 'CV1', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('LXDDOCDEV1', 'Doc. dev. romaneio', 'LXD', 'CV1', 'CV1DOCFIS', '', 'C', 3, 0, 0, 1, 0, 1, 'Documento fiscal de devolução para romaneios', 'CV1', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('LXDDOCDEV2', 'Doc. dev. cons rom', 'LXD', 'CV1', 'CV1DOCFIS', '', 'C', 3, 0, 0, 1, 0, 1, 'Documento fiscal de devolução para consignado em romaneio', 'CV1', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('LXDDOCDEV3', 'Doc. dev. NF', 'LXD', 'CV1', 'CV1DOCFIS', '', 'C', 3, 0, 0, 1, 0, 1, 'Documento fiscal de devolução para nota fiscal', 'CV1', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('LXDDOCDEV4', 'Doc. dev. cons. NF', 'LXD', 'CV1', 'CV1DOCFIS', '', 'C', 3, 0, 0, 1, 0, 1, 'Documento fiscal de devolução para consignado em nota fiscal', 'CV1', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('LXDDEVVEN', 'Trocar na venda', 'LXD', '', '', '', 'N', 1, 0, 0, 0, 1, 0, '0 = não;1 = sim - Permite realizar a manutenção das peças de troca na tela de venda', '', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('LXDCONSNF', 'Gerar NF Consignado', 'LXD', '', '', '', 'N', 1, 0, 0, 0, 1, 0, '0 = não;1 = sim - Gerar obrigatóriamente a NF para venda consignada', '', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('LXDULTGUIA', 'Último guia', 'LXD', '', '', '', 'N', 1, 0, 0, 0, 1, 0, '0 = não;1 = sim - Preencher na tela de venda o guia da última venda', '', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('LXDMOTIDEV', 'Motivo padrão Devolução', 'LXD', 'VD0', 'VD0MOTIVO', '', 'C', 2, 0, 0, 1, 1, 0, 'Motivo da devolução e cancelamento do item do pedido.', 'VD0', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('LXDENTRDEV', 'Entrada na devolução', 'LXD', '', '', '', 'N', 1, 0, 0, 0, 1, 0, 'Permite realizar entrada de peças durante a devolução.', '', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('LXDDOCENT1', 'Doc. ent. romaneio', 'LXD', 'CV1', 'CV1DOCFIS', '', 'C', 3, 0, 0, 1, 1, 1, 'Documento fiscal para entrada de peças que não possuem saldo para devolução', 'CV1', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('LXDDOCENT2', 'Doc. ent. cons rom', 'LXD', 'CV1', 'CV1DOCFIS', '', 'C', 3, 0, 0, 1, 1, 1, 'Documento fiscal para entrada de peças consignadas que não possuem saldo para devolução', 'CV1', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('LXDDESCDEV', 'Desconto na devolução', 'LXD', '', '', '', 'N', 1, 0, 0, 0, 1, 0, 'Habilita recuperar descontos na devolução de produtos.', '', 0, '');

CREATE TABLE PD0 (
  PD0CODIGO char(3) NOT NULL,
  PD0NOME CHAR(20) DEFAULT ' ',
  PD0ANTENA CHAR(2) DEFAULT ' ',
  PD0CAMINHO CHAR(100) DEFAULT ' ',
  PRIMARY KEY (PD0CODIGO)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO DC0 (DC0ARQUIVO,DC0NOME,DC0ACESSO,DC0NAOIMP,DC0NAOEXP,DC0CONEXAO,DC0TIPO)  values ('PD0','Terminais de venda',0,0,0,1,0);

Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('PD0CODIGO', 'Terminal', 'PD0', '', '', '', 'C', 3, 0, 0, 1, 0, 1, 'Código do terminal', '', 1, '000');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('PD0NOME', 'Nome', 'PD0', '', '', '', 'C', 20, 0, 0, 0, 0, 0, 'Nome do terminal', '', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('PD0ANTENA', 'Antena RFID', 'PD0', '', '', '', 'C', 50, 0, 0, 0, 0, 0, 'Código do grupo da antena do terminal', '', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('PD0CAMINHO', 'Caminho rede', 'PD0', '', '', '', 'C', 100, 0, 0, 0, 0, 0, 'Caminho de rede do terminal', '', 0, '');


CREATE TABLE PD1 (
  PD1CODIGO char(3) NOT NULL,
  PD1RELAT CHAR(3) NOT NULL,
  PD1IMPRES CHAR(50) DEFAULT ' ',
  PRIMARY KEY (PD1CODIGO,PD1RELAT)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO DC0 (DC0ARQUIVO,DC0NOME,DC0ACESSO,DC0NAOIMP,DC0NAOEXP,DC0CONEXAO,DC0TIPO)  values ('PD1','Preferências impressão',0,0,0,1,0);

Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('PD1CODIGO', 'Terminal', 'PD1', 'PD0', 'PD0CODIGO', '', 'C', 3, 0, 0, 1, 0, 1, 'Código do terminal', 'PD0', 1, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('PD1RELAT', 'Relatório', 'PD1', 'DC9', 'DC9RELAT', '', 'C', 3, 0, 0, 1, 0, 1, 'Código do relatório', 'DC9', 1, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('PD1IMPRES', 'Impressora Padrão', 'PD1', '', '', '', 'C', 50, 0, 0, 0, 0, 0, 'Impressora Padrão a ser impressa o documento', '', 0, '');

CREATE TABLE PD2 (
  PD2CODIGO INT AUTO_INCREMENT PRIMARY KEY,
  PD2TIPOOPE decimal(1,0) DEFAULT 0,
  PD2TIPO CHAR(3) NOT NULL,
  PD2ESTADUA DECIMAL(1,0) DEFAULT 0,
  PD2CONTRIB DECIMAL(1,0) DEFAULT 0,
  PD2OPERCOM CHAR(3) NOT NULL,
  PD2EMISPRO DECIMAL(1,0) DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

create index salesOperation on PD2(PD2TIPOOPE,PD2TIPO,PD2ESTADUA,PD2CONTRIB);

INSERT INTO DC0 (DC0ARQUIVO,DC0NOME,DC0ACESSO,DC0NAOIMP,DC0NAOEXP,DC0CONEXAO,DC0TIPO)  values ('PD2','Parâmetros op. de venda',0,0,0,1,0);

Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('PD2CODIGO', 'Código', 'PD2', '', '', '', 'N', 6, 0, 0, 0, 0, 1, 'Código de identificação', '', 1, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('PD2TIPOOPE', 'Tipo operação', 'PD2', '', '', '', 'N', 1, 0, 0, 0, 0, 1, 'Tipo de operação de venda: 0 = nenhum; 1 = venda; 2 = Devolução; 3 = saída consig.; 4 = Entrada consig.', '', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('PD2TIPO', 'Tipo documento', 'PD2', 'CV1', 'CV1DOCFIS', '', 'C', 3, 0, 0, 1, 0, 1, 'Tipo de documento fiscal', 'CV1', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('PD2ESTADUA', 'Interestadual', 'PD2', '', '', '', 'N', 1, 0, 0, 0, 0, 1, '0 = estadual; 1 = interestadual', '', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('PD2CONTRIB', 'Contribuinte ICMS', 'PD2', '', '', '', 'N', 1, 0, 0, 0, 0, 1, '0 = não contribuinte; 1 = Contribuinte', '', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('PD2OPERCOM', 'Operação Comercial', 'PD2', 'CV3', 'CV3OPERCOM', '', 'C', 3, 0, 0, 1, 0, 1, 'Operação comercial', 'CV3', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('PD2EMISPRO', 'Emissão Própria', 'PD2', '', '', '', 'N', 1, 0, 0, 0, 0, 1, 'Determina se o documento fiscal é de emissão própria.', '', 0, '');

CREATE TABLE FNL(FNLCLIENTE CHAR(14) NOT NULL ,
FNLEMISSOR CHAR(14),
FNLTIPO CHAR(3),
FNLDOC CHAR(6),
FNLCREDITO NUMERIC(12,2) DEFAULT 0,
FNLDATACRE DATETIME,
PRIMARY KEY (FNLEMISSOR, FNLTIPO, FNLDOC, FNLCLIENTE));
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) values ('FNLCLIENTE', 'Cnpj ou Cpf', 'FNL', 'CF1', 'CF1CLIENTE', '', 'C', 14, 0, 0, 0, 0, 4, 'Cnpj ou Cpf do cliente com crédito', 'CF1', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) values ('FNLCREDITO', 'Crédito do Cliente', 'FNL', '', '', '', 'N', 12, 2, 0, 0, 0, 0, 'Crédito do cliente disponível para compra', '', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('FNLDATACRE', 'Data do crédito', 'FNL', '', '', '', 'T', 8, 0, 0, 5, 0, 0, 'Data do documento para crédito da loja', '', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME, DC1ARQUIVO, DC1ARQPAI, DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) values ('FNLTIPO','Tipo','FNL','CV1','CV1DOCFIS','','C',3,0,0,0,0,2,'Tipo de documento fiscal de emissão própria.','CV1',0,'');
Insert into DC1 (DC1CAMPO,DC1NOME, DC1ARQUIVO, DC1ARQPAI, DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) values ('FNLDOC','Documento','FNL','','','','C',6,0,0,1,0,3,'Número incremental do documento emitido.','',0,'');
Insert into DC1 (DC1CAMPO,DC1NOME, DC1ARQUIVO, DC1ARQPAI, DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) values ('FNLEMISSOR','Cnpj/Cic do Emitente ','FNL','CF1','CF1CLIENTE','','C',14,0,1,0,0,1,'Cnpj ou Cic do emitente do documento.','',0,'');
INSERT INTO DC0 (DC0ARQUIVO,DC0NOME,DC0ACESSO,DC0NAOIMP,DC0NAOEXP,DC0CONEXAO,DC0TIPO) values ('FNL','Crédito para compra',0,0,0,1,0);




ALTER TABLE TOK MODIFY COLUMN TOKLOGIN CHAR(15) DEFAULT ' ';
UPDATE DC1 SET DC1TAMANHO = 15 WHERE DC1CAMPO = 'TOKLOGIN';


-- PD3 - TELA PRINCIPAL DO CAIXA
INSERT INTO DC0 (DC0ARQUIVO,DC0NOME,DC0ACESSO,DC0NAOIMP,DC0NAOEXP,DC0CONEXAO,DC0TIPO)  values ('PD3','Principal',0,0,0,1,0);

-- INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('PD3ESTATIS','Estatísticas','PD3','','','','C',1,0,0,0,0,1,'Campo exclusivamente para chave','',0,'');
-- PD4 - CARRINHO/VENDA
INSERT INTO DC0 (DC0ARQUIVO,DC0NOME,DC0ACESSO,DC0NAOIMP,DC0NAOEXP,DC0CONEXAO,DC0TIPO)  values ('PD4','Carrinho',0,0,0,1,0);

-- PDV - TELA PRINCIPAL DO PDV
INSERT INTO DC0 (DC0ARQUIVO,DC0NOME,DC0ACESSO,DC0NAOIMP,DC0NAOEXP,DC0CONEXAO,DC0TIPO)  values ('PDV','Início',0,0,0,1,0);


CREATE TABLE  vdv (
  VDVVOLUME CHAR(6) NOT NULL,
  VDVPECA CHAR(12) NOT NULL,
  VDVPRECO DECIMAL(10,2) DEFAULT '0.00',
  VDVLEITURA DATETIME NOT NULL DEFAULT '1899-12-30 00:00:00',
  VDVQTDE DECIMAL(4,0) DEFAULT 0,
  VDVPRODUTO CHAR(5) NOT NULL,
  VDVOPCAO CHAR(3) NOT NULL,
  VDVTAMANHO CHAR(3) NOT NULL,
  PRIMARY KEY (VDVVOLUME, VDVPECA, VDVPRODUTO, VDVOPCAO, VDVTAMANHO),
  KEY VDVPECA (VDVPECA),
  KEY VDVVOLUME (VDVVOLUME),
  KEY VDVLEITURA (VDVLEITURA, VDVPECA),
  KEY VDVPRODUTO (VDVPRODUTO, VDVOPCAO, VDVTAMANHO)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO DC0 (DC0ARQUIVO,DC0NOME,DC0ACESSO,DC0NAOIMP,DC0NAOEXP,DC0CONEXAO,DC0TIPO) VALUES ('VDV', 'Itens Expedidos', 0, 0, 0, 0, 1);

INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('VDVLEITURA', 'Data/Hora Leitura', 'VDV', '', '', '', 'T', 8, 0, 0, 0, 0, 0, 'Data e hora em que a peça foi incluída no volume', '', 2, '');
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('VDVPECA', 'N Peca', 'VDV', 'EAN', 'EANCODIGO', '', 'C', 12, 0, 0, 1, 1, 2, 'Número da Peça embarcada.', '', 0, '');
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('VDVPRECO', 'Preço', 'VDV', '', '', '', 'N', 10, 2, 0, 0, 0, 0, 'Preço da peça no Pedido', '', 2, '');
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('VDVVOLUME', 'Volume', 'VDV', 'VD7', 'VD7VOLUME', '', 'C', 6, 0, 0, 1, 0, 1, 'Número do volume.', '', 0, '');
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('VDVQTDE', 'Qtde', 'VDV', '', '', '', 'N', 4, 0, 1, 0, 1, 0, 'Quantidade pedida', '', 0, '');
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('VDVPRODUTO', 'Produto', 'VDV', 'PR0', 'PR0PRODUTO', '', 'C', 5, 0, 0, 1, 0, 2, 'Produto pedido', 'PR0', 0, '');
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('VDVOPCAO', 'Cor', 'VDV', 'PR2', 'PR2OPCAO', '', 'C', 3, 0, 0, 1, 1, 3, 'Opção de Cor', 'PR2', 0, '');
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('VDVTAMANHO', 'Tam', 'VDV', 'PR3', 'PR3TAMANHO', '', 'C', 3, 0, 1, 0, 0, 4, 'Código do tamanho', 'PR3', 0, '');

CREATE TABLE  vdx (
  VDXDOC char(5) NOT NULL,
  VDXPECA char(12) NOT NULL,
  VDXLEITURA datetime NOT NULL DEFAULT '1899-12-30 00:00:00',
  VDXVOLUME char(6) DEFAULT '',
  VDXGRAVOU decimal(1,0) DEFAULT '0',
  VDXPRECO decimal(10,2) DEFAULT '0.00',
  VDXPEDIDO char(6) DEFAULT '',
  VDXQTDE decimal(4,0) default 0,
  VDXPRODUTO CHAR(5) NOT NULL,
  VDXOPCAO CHAR(3) NOT NULL,
  VDXTAMANHO CHAR(3) NOT NULL,
  VDXITEM CHAR(3) NOT NULL,
  PRIMARY KEY (VDXDOC,VDXITEM)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO DC0 (DC0ARQUIVO,DC0NOME,DC0ACESSO,DC0NAOIMP,DC0NAOEXP,DC0CONEXAO,DC0TIPO) VALUES ('VDX', 'Peças Devolvidas', 0, 0, 0, 0, 1);

INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('VDXDOC', 'Documento de Devolução', 'VDX', 'VDK', 'VDKDOC', '', 'C', 5, 0, 0, 1, 0, 1, 'Documento de devolução.', '', 0, '');
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('VDXGRAVOU', 'Flag', 'VDX', '', '', '', 'N', 1, 0, 0, 0, 0, 0, 'Flag de Gravação do cancelamento e estorno da saída no volume.', '', 0, '');
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('VDXLEITURA', 'Data/Hora Leitura', 'VDX', '', '', '', 'T', 8, 0, 0, 5, 0, 0, 'Data e hora em que a peça foi lida.', '', 0, '');
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('VDXPECA', 'Id Peca', 'VDX', 'EAN', 'EANCODIGO', '', 'C', 12, 0, 0, 1, 0, 2, 'Identificação da peça devolvida.', '', 0, '');
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('VDXPEDIDO', 'Pedido', 'VDX', 'VD1', 'VD1PEDIDO', '', 'C', 6, 0, 0, 1, 1, 0, 'Número do pedido em que a peça foi espedida.', '', 0, '');
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('VDXPRECO', 'Preço', 'VDX', '', '', '', 'N', 10, 2, 0, 0, 0, 0, 'Preço com que o produto foi expedido.', '', 0, '');
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('VDXVOLUME', 'Volume', 'VDX', '', '', '', 'C', 6, 0, 0, 1, 1, 0, 'Volume em que se encontrava a peça.', '', 0, '');
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('VDXQTDE', 'Qtde', 'VDX', '', '', '', 'N', 4, 0, 1, 0, 1, 0, 'Quantidade pedida', '', 0, '');
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('VDXPRODUTO', 'Produto', 'VDX', 'PR0', 'PR0PRODUTO', '', 'C', 5, 0, 0, 1, 0, 2, 'Produto devolvido', 'PR0', 0, '');
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('VDXOPCAO', 'Cor', 'VDX', 'PR2', 'PR2OPCAO', '', 'C', 3, 0, 0, 1, 1, 3, 'Opção de Cor', 'PR2', 0, '');
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('VDXTAMANHO', 'Tam', 'VDX', 'PR3', 'PR3TAMANHO', '', 'C', 3, 0, 1, 0, 0, 4, 'Código do tamanho', 'PR3', 0, '');
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('VDXITEM', 'N Item', 'VDX', '', '', '', 'C', 3, 0, 0, 0, 0, 4, 'Número do Ítem no documento.', '', 2, '');


-- RODAR EM BASES EXISTENTES
/*ALTER TABLE VDX ADD COLUMN VDXITEM CHAR(3) NOT NULL;

ALTER TABLE VDX DROP PRIMARY KEY;

ALTER TABLE VDX ADD PRIMARY KEY(VDXDOC,VDXITEM);
*/

CREATE TABLE PD5 (
  PD5CODIGO INT AUTO_INCREMENT PRIMARY KEY,
  PD5TIPINSH decimal(1,0) DEFAULT 0,
  PD5URL CHAR(250) DEFAULT ' ',
  PD5USUARIO CHAR(20) DEFAULT ' ',
  PD5SENHA CHAR(20) DEFAULT ' '
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO DC0 (DC0ARQUIVO,DC0NOME,DC0ACESSO,DC0NAOIMP,DC0NAOEXP,DC0CONEXAO,DC0TIPO)  values ('PD5','Parâmetros shopping',0,0,0,1,0);

Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('PD5CODIGO', 'Código', 'PD5', '', '', '', 'N', 6, 0, 0, 0, 0, 1, 'Código de identificação', '', 2, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('PD5TIPINSH', 'Tipo int. Shop.', 'PD5', '', '', '', 'N', 1, 0, 0, 0, 1, 0, 'Define o tipo de integração com shopping', '', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('PD5URL', 'URL integração', 'PD5', '', '', '', 'C', 250, 0, 0, 0, 0, 0, 'Url integração com shopping', '', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('PD5USUARIO', 'Usuário', 'PD5', '', '', '', 'C', 20, 0, 0, 0, 0, 0, 'Usuário de integração', '', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('PD5SENHA', 'Senha', 'PD5', '', '', '', 'C', 20, 0, 1, 0, 1, 0, 'Senha de integração', '', 0, '');



-- oryxgestao
CREATE TABLE PD6( PD6EMISSOR CHAR(14) NOT NULL ,
PD6AGENTEP CHAR(3),
PD6CRUZAR NUMERIC(1),
PD6IMPRES CHAR(50) DEFAULT ' ',
PD6NOMINAL CHAR(50) DEFAULT ' ',
PRIMARY KEY (PD6EMISSOR));

Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('PD6EMISSOR','Cnpj/CPF','PD6','CF1','CF1CLIENTE','       ','C',14,0,0,0,0,1,'Cnpj ou CPF do emitente','CF1',0,'');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('PD6AGENTEP','Código do banco padrão','PD6','','','','C',3,0,0,1,0,0,'Código padrão do banco para posições impressões do layout','',0,'');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('PD6CRUZAR','Cheque cruzado','PD6','','','','N',1,0,0,0,0,0,'Define se o cheque vai ser cruzado na impressão','',0,'');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('PD6IMPRES', 'Impressora Padrão', 'PD6', '', '', '', 'C', 50, 0, 0, 0, 0, 0, 'Impressora Padrão a ser impressa o documento', '', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('PD6NOMINAL', 'Nominal cheque', 'PD6', '', '', '', 'C', 50, 0, 0, 0, 0, 0, 'Impressão nominal no cheque', '', 0, '');


CREATE TABLE PD7( PD7EMISSOR CHAR(14) NOT NULL ,
PD7AGENTE CHAR(3) NOT NULL,
PD7VALOR CHAR(7) NOT NULL,
PD7LINHA1 CHAR(7) NOT NULL,
PD7LINHA2 CHAR(7) NOT NULL,
PD7NOMINAL CHAR(7) NOT NULL,
PD7CIDADE CHAR(7) NOT NULL,
PD7DIA CHAR(7) NOT NULL,
PD7MES CHAR(7) NOT NULL,
PD7ANO CHAR(7) NOT NULL,
PD7BOMPARA CHAR(7) NOT NULL,
PRIMARY KEY (PD7EMISSOR,PD7AGENTE));


Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('PD7EMISSOR','Cnpj/CPF','PD7','CF1','CF1CLIENTE','       ','C',14,0,0,0,0,1,'Cnpj ou CPF do emitente','CF1',0,'');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('PD7AGENTE','Código do banco','PD7','','','','C',3,0,0,0,0,2,'Código do banco para configuração de posição','',0,'');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('PD7VALOR','Posição valor','PD7','','','','C',7,0,0,0,0,0,'Posição do valor a ser impresso no cheque','',0,'');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('PD7LINHA1','Posição 1º linha','PD7','','','','C',7,0,0,0,0,0,'Posição da primeira linha a ser impresso no cheque','',0,'');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('PD7LINHA2','Posição 2º linha','PD7','','','','C',7,0,0,0,0,0,'Posição da segunda linha a ser impresso no cheque','',0,'');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('PD7NOMINAL', 'Posição nominal', 'PD7', '', '', '', 'C', 7, 0, 0, 0, 0, 0, 'Posição nominal a ser impresso no cheque', '', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('PD7CIDADE','Posição da cidade','PD7','','','','C',7,0,0,0,0,0,'Posição da cidade a ser impresso no cheque','',0,'');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('PD7DIA','Posição do dia','PD7','','','','C',7,0,0,0,0,0,'Posição do dia a ser impresso no cheque','',0,'');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('PD7MES','Posição do mês','PD7','','','','C',7,0,0,0,0,0,'Posição do mês a ser impresso no cheque','',0,'');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('PD7ANO','Posição do ano','PD7','','','','C',7,0,0,0,0,0,'Posição do ano a ser impresso no cheque','',0,'');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('PD7BOMPARA','Posição bom para','PD7','','','','C',7,0,0,0,0,0,'Posição da data de compensação a ser impresso no cheque','',0,'');


INSERT INTO DC0 (DC0ARQUIVO,DC0NOME,DC0ACESSO,DC0NAOIMP,DC0NAOEXP,DC0CONEXAO,DC0TIPO)  values ('PD6','Parâmetros cheques',0,0,0,1,0);
INSERT INTO DC0 (DC0ARQUIVO,DC0NOME,DC0ACESSO,DC0NAOIMP,DC0NAOEXP,DC0CONEXAO,DC0TIPO)  values ('PD7','Posições cheques',0,0,0,1,0);
INSERT INTO PD6 (PD6EMISSOR,PD6AGENTEP,PD6CRUZAR,PD6IMPRES,PD6NOMINAL) VALUES((select lx0cliente from lx0),'001','0','','');
INSERT INTO PD7 (PD7EMISSOR,PD7AGENTE,PD7VALOR,PD7LINHA1,PD7LINHA2,PD7NOMINAL,PD7CIDADE,PD7DIA,PD7MES,PD7ANO,PD7BOMPARA) VALUES ((select lx0cliente from lx0),'001','754,206','413,230','354,250','354,270','580,286','649,286','718,286','805,286','754,380');

-- todos os módulos
CREATE TABLE LXE (
  LXEPADRAO char(1) DEFAULT NULL,
  LXEBASEURL CHAR(250) DEFAULT ' ',
  LXEIMAGSER CHAR(254) DEFAULT '',
  PRIMARY KEY (LXEPADRAO)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO DC0 (DC0ARQUIVO,DC0NOME,DC0ACESSO,DC0NAOIMP,DC0NAOEXP,DC0CONEXAO,DC0TIPO)  values ('LXE','Parâmetros de API',0,0,0,1,0);

Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('LXEPADRAO','Padrão de APIs','LXE','','','','C',1,0,0,0,0,1,'Campo exclusivamente para chave','',0,'');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('LXEBASEURL', 'URL Microserviços', 'LXE', '', '', '', 'C', 250, 0, 0, 0, 0, 0, 'Url base dos microserviços', '', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('LXEIMAGSER', 'Caminho das imagens', 'LXE', '', '', '', 'C', 254, 0, 0, 0, 0, 0, 'Caminho no qual as imagens serão armazenadas.', '', 0, '');


-- alterações dicionário para PDV
update dc1 set dc1nulo = 1 where dc1campo in ('VD1TRANSP', 'cv5ecf', 'cv5totaliz', 'cv5situa', 'cv5tipolig', 'cv5tensao', 'cv5codcons');

-- garantia de tipo cv7 campo cv7qcon
UPDATE dc1 SET DC1TIPO = 'D' WHERE (DC1ARQUIVO = 'CV7' and DC1CAMPO = 'CV7QCOM');

-- VD5OPCAO
ALTER TABLE VD5 ADD COLUMN VD5OPCAO CHAR(3) DEFAULT NULL;
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('VD5OPCAO', 'Cor', 'VD5', 'PR2', 'PR2OPCAO', 'VD5PRODUTO=PR2PRODUTO', 'C', 3, 0, 0, 1, 1, 3, 'Opção de Cor', 'PR2', 0, '');

alter table vd5 drop primary key;

alter table vd5 add primary key (vd5pedido, vd5produto, vd5tamanho, vd5opcao);

-- CV7BASEICP
alter table cv7 add column CV7BASEICP decimal(7,3) default 0.00;
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('CV7BASEICP', 'Base ICMS %', 'CV7', '', '', '', 'N', 7, 3, 0, 0, 1, 0, 'Base ICMS do item em percentual.', '', 0, '');

-- vdkmotivo
UPDATE DC1 SET DC1NULO = 1 WHERE DC1CAMPO = 'VDKMOTIVO';

-- caso o cliente for trabalhar com referencia
-- ALTER TABLE VD3 MODIFY VD3OPCAO CHAR(3);
-- ALTER TABLE VD3 MODIFY VD3TAMANHO CHAR(3);

-- deixando campos tamanho do pedido não obrigatórios PARA QUEM UTILIZAR VENDA APENAS POR REFERÊNCIA
UPDATE DC1 SET DC1NULO = 1 WHERE DC1CAMPO = 'VD3TAMANHO';
UPDATE DC1 SET DC1NULO = 1 WHERE DC1CAMPO = 'VD5TAMANHO';
UPDATE DC1 SET DC1NULO = 1 WHERE DC1CAMPO = 'VDVTAMANHO';
UPDATE DC1 SET DC1NULO = 1 WHERE DC1CAMPO = 'CV7TAMANHO';
UPDATE DC1 SET DC1NULO = 1 WHERE DC1CAMPO = 'VDXPECA';
UPDATE DC1 SET DC1NULO = 1 WHERE DC1CAMPO = 'VDXTAMANHO';
UPDATE DC1 SET DC1NULO = 1 WHERE DC1CAMPO = 'VDZTAMANHO';
UPDATE DC1 SET DC1NULO = 1 WHERE DC1CAMPO = ' CV8CMC7';

UPDATE DC1 SET DC1ESPACO = 1 WHERE DC1CAMPO = 'CV7INFADIC';
UPDATE DC1 SET DC1ESPACO = 1 WHERE DC1CAMPO = ' CV8CMC7';

-- UPDATE CV3 SET CV3EAN = 0, CV3GS1INT = 0;

ALTER TABLE VD6 ADD COLUMN VD6DOCCONF CHAR(5) DEFAULT ' ';
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('VD6DOCCONF', 'Confirmação de Venda', 'VD6', 'VDE', 'VDEDOC', '', 'C', 5, 0, 0, 1, 1, 0, 'Documento de confirmação de venda.', '', 2, '');


CREATE TABLE  vdz (
  VDZDOC CHAR(6) NOT NULL,
  VDZPECA CHAR(12) NOT NULL,
  VDZLEITURA DATETIME NOT NULL DEFAULT '1899-12-30 00:00:00',
  VDZQTDE DECIMAL(4,0) DEFAULT 0,
  VDZPRODUTO CHAR(5) NOT NULL,
  VDZOPCAO CHAR(3) NOT NULL,
  VDZTAMANHO CHAR(3) NOT NULL,
  PRIMARY KEY (VDZDOC, VDZPECA, VDZPRODUTO, VDZOPCAO, VDZTAMANHO),
  KEY VDZPECA (VDZPECA),
  KEY VDZDOC (VDZDOC),
  KEY VDZPRODUTO (VDZPRODUTO, VDZOPCAO, VDZTAMANHO)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO DC0 (DC0ARQUIVO,DC0NOME,DC0ACESSO,DC0NAOIMP,DC0NAOEXP,DC0CONEXAO,DC0TIPO) VALUES ('VDZ', 'Itens Confirmados', 0, 0, 0, 0, 1);
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('VDZDOC', 'Documento de Confirmação', 'VDZ', 'VDE', 'VDEDOC', '', 'C', 5, 0, 0, 1, 0, 1, 'Documento de confirmação/contagem de venda consignada.', '', 0, '');
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('VDZLEITURA', 'Data/Hora Leitura', 'VDZ', '', '', '', 'T', 8, 0, 0, 0, 0, 0, 'Data e hora em que a peça foi incluída na confirmação/contagem de venda consignada', '', 2, '');
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('VDZPECA', 'N Peca', 'VDZ', 'EAN', 'EANCODIGO', '', 'C', 12, 0, 0, 1, 1, 2, 'Número da Peça confirmada.', '', 0, '');
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('VDZQTDE', 'Qtde', 'VDZ', '', '', '', 'N', 4, 0, 1, 0, 1, 0, 'Quantidade pedida confirmada', '', 0, '');
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('VDZPRODUTO', 'Produto', 'VDZ', 'PR0', 'PR0PRODUTO', '', 'C', 5, 0, 0, 1, 0, 2, 'Produto pedido', 'PR0', 0, '');
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('VDZOPCAO', 'Cor', 'VDZ', 'PR2', 'PR2OPCAO', '', 'C', 3, 0, 0, 1, 1, 3, 'Opção de Cor', 'PR2', 0, '');
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('VDZTAMANHO', 'Tam', 'VDZ', 'PR3', 'PR3TAMANHO', '', 'C', 3, 0, 1, 0, 0, 4, 'Código do tamanho', 'PR3', 0, '');

-- CRIADO CAMPO HOST NA TABELA PD0
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('PD0HOST', 'Host do terminal', 'PD0', '', '', '', 'C', 15, 0, 0, 1, 1, 0, 'Host configurado na maquina.', '', 2, '');
ALTER TABLE PD0 ADD  PD0HOST VARCHAR(15);
-- CRIAÇÃO DE TERMINAL DEFAULT
INSERT INTO PD0 VALUES ('000', 'Terminal default','','','');

-- UPDATE PARA TODOS OS RELATÓRIOS UTILIZADOS PELO PDV - PRECISA ESTAR SETADO ESSA INFORMAÇÃO PARA IMPRIMIR SEM SOLICITAR A IMPRESSORA
UPDATE DC9 SET DC9IMPRES = 4 WHERE DC9RELAT IN ('031', '270', '144');

-- ajuste campo local do endereço
UPDATE DC1 SET DC1TAMANHO = '7' WHERE DC1CAMPO IN ('CF2LOCAL', 'CF3LOCAL');

UPDATE DC1 SET DC1NULO = 1 WHERE DC1CAMPO = 'CV8CMC7';

ALTER TABLE CV5 ADD COLUMN CV5CAMBIO DECIMAL(12,6) DEFAULT 0.000000;
ALTER TABLE CV5 ADD COLUMN CV5CBENEF CHAR(10) DEFAULT '';
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('CV5CAMBIO', 'Taxa Cambial', 'CV5', '', '', '', 'N', 12, 6, 0, 0, 0, 0, 'Cotação da Moeda estrangeira(pais) para moeda nacional', '', 2, '');
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('CV5CBENEF', 'Código do Benef Fiscal', 'CV5', '', '', '', 'C', 10, 0, 0, 0, 1, 0, 'Código do cbenef para beneficios fiscais', '', 0, '');

-- ajuste tabela tecdatasoft
ALTER TABLE TECDATASOFT MODIFY COLUMN CV7SUBTOT DECIMAL(9,2);


-- A PARTIR DAQUI SÃO ALTERAÇÕES

ALTER TABLE LXD ADD COLUMN LXDENTRDEV DECIMAL(1,0) DEFAULT 0;
ALTER TABLE LXD ADD COLUMN LXDDOCENT1 CHAR(3) DEFAULT '';
ALTER TABLE LXD ADD COLUMN LXDDOCENT2 CHAR(3) DEFAULT '';
ALTER TABLE LXD ADD COLUMN LXDDESCDEV DECIMAL(1,0) DEFAULT 0;
ALTER TABLE LXD ADD COLUMN LXDMERCADO DECIMAL(1,0) DEFAULT 0;

INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('LXDMERCADO', 'Modo mercado', 'LXD', '', '', '', 'N', 1, 0, 0, 0, 1, 0, 'Habilita modo consumidor final no sistema.', '', 0, '');

UPDATE DC1 SET DC1NULO = 1 WHERE DC1CAMPO IN ('VDXVOLUME', 'VDXPEDIDO', 'CV5TRENDER', 'PD0ANTENA', 'PD0CAMINHO', 'LXDDOCENT1', 'LXDDOCENT2', 'LXDDOCDEV4');

update dc1 set dc1tamanho = 9 where dc1campo = 'VD1DESCON';

ALTER TABLE VD1 MODIFY COLUMN VD1DESCON DECIMAL(9,2);

-- alter565

CREATE TABLE  CX0 (
  CX0CAIXA CHAR(6) NOT NULL,
  CX0ABERT DATETIME NOT NULL,
  CX0FECHA DATETIME DEFAULT '1899-12-30 00:00:00',
  CX0USUABE CHAR(3) NOT NULL,
  CX0USUFEC CHAR(3) DEFAULT '',
  CX0VALINI DECIMAL(7,2) DEFAULT 0,
  CX0CODIGO CHAR(3) NOT NULL,
  PRIMARY KEY (CX0CAIXA)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO DC0 (DC0ARQUIVO,DC0NOME,DC0ACESSO,DC0NAOIMP,DC0NAOEXP,DC0CONEXAO,DC0TIPO) VALUES ('CX0', 'Caixas', 0, 0, 0, 0, 1);
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('CX0CAIXA', 'Código do caixa', 'CX0', '', '', '', 'C', 6, 0, 0, 1, 0, 1, 'Código idenficador do caixa.', '', 0, '');
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('CX0ABERT', 'Data/Hora abertura', 'CX0', '', '', '', 'T', 8, 0, 0, 0, 0, 0, 'Data e hora em que o caixa foi aberto.', '', 1, '');
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('CX0FECHA', 'Data/Hora Fechamento', 'CX0', '', '', '', 'T', 8, 0, 0, 0, 1, 0, 'Data e hora em que o caixa foi fechado.', '', 1, '');
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('CX0USUABE', 'Usuário abertura', 'CX0', 'DC4', 'DC4USUARIO', '', 'C', 3, 0, 0, 1, 0, 0, 'Usuário responsável pela abertura do caixa', 'DC4', 1, '');
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('CX0USUFEC', 'Usuário fechamento', 'CX0', 'DC4', 'DC4USUARIO', '', 'C', 3, 0, 0, 1, 1, 0, 'Usuário responsável pelo fechamento do caixa', 'DC4', 1, '');
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('CX0VALINI', 'Valor inicial', 'CX0', '', '', '', 'N', 7, 2, 0, 0, 1, 0, 'Valor inicial do caixa durante a abertura', '', 1, '');
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('CX0CODIGO', 'Terminal', 'CX0', 'PD0', 'PD0CODIGO', '', 'C', 3, 0, 0, 1, 0, 0, 'Terminal utilizado para abertura do caixa', 'PD0', 1, '');

CREATE TABLE  CX1 (
  CX1REGISTR CHAR(8) NOT NULL,
  CX1CAIXA CHAR(6) NOT NULL,
  CX1TIPO DECIMAL(1,0) DEFAULT 0,
  CX1VALOR DECIMAL(7,2) DEFAULT 0,
  CX1DATA DATETIME NOT NULL,
  CX1ENTSAI DECIMAL(1,0) DEFAULT 0,
  PRIMARY KEY (CX1REGISTR)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO DC0 (DC0ARQUIVO,DC0NOME,DC0ACESSO,DC0NAOIMP,DC0NAOEXP,DC0CONEXAO,DC0TIPO) VALUES ('CX1', 'Movimentos de caixa', 0, 0, 0, 0, 1);
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('CX1REGISTR', 'Código da movimentação', 'CX1', '', '', '', 'C', 8, 0, 0, 1, 0, 1, 'Código idenficador da movimentação do caixa.', '', 0, '');
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('CX1CAIXA', 'Código do caixa', 'CX1', 'CX0', 'CX0CAIXA', '', 'C', 6, 0, 0, 1, 0, 0, 'Código idenficador do caixa.', 'CX0', 1, '');
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('CX1TIPO', 'Tipo de movimento', 'CX1', '', '', '', 'N', 1, 0, 0, 0, 0, 0, 'Tipo de movimentação realizada no caixa.', '', 1, '');
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('CX1VALOR', 'Valor', 'CX1', '', '', '', 'N', 7, 2, 0, 0, 0, 0, 'Valor movimentado', '', 0, '');
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('CX1DATA', 'Data/Hora movimento', 'CX1', '', '', '', 'T', 8, 0, 0, 0, 0, 0, 'Data e hora em que foi realizada a movimentação no caixa.', '', 1, '');
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('CX1ENTSAI', 'Fluxo de caixa', 'CX1', '', '', '', 'N', 1, 0, 0, 0, 0, 0, 'Tipo de fluxo de caixa (0 = nenhum, 1 = saída, 2 = entrada)', '', 1, '');


ALTER TABLE CV5 ADD COLUMN CV5CAIXA CHAR(6) DEFAULT '';
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('CV5CAIXA', 'Código do caixa', 'CV5', 'CX0', 'CX0CAIXA', '', 'C', 6, 0, 0, 1, 1, 0, 'Código idenficador do caixa da venda.', 'CX0', 0, '');

ALTER TABLE LXD ADD COLUMN LXDCAIXA DECIMAL(1,0) DEFAULT 0;
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('LXDCAIXA', 'Ativar caixa', 'LXD', '', '', '', 'N', 1, 0, 0, 0, 1, 0, 'Ativa sistema de caixa no sistema', '', 0, '');

UPDATE DC1 SET DC1EDICAO = 0, DC1FORMATO = 0 WHERE DC1CAMPO = 'PD0HOST';

ALTER TABLE PD1 ADD COLUMN PD1VIAS decimal(1,0) default 0;
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('PD1VIAS', 'Número de vias', 'PD1', '', '', '', 'N', 1, 0, 0, 0, 0, 0, 'Número de vias a serem impressas durante a impressão de documentos', '', 0, '');

UPDATE PD1 SET PD1VIAS = 1 WHERE PD1VIAS = 0;

ALTER TABLE LXD ADD COLUMN LXDETIQVOL DECIMAL(1,0) DEFAULT 0;
ALTER TABLE LXD ADD COLUMN LXDTIPETIQ DECIMAL(1,0) DEFAULT 0;
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('LXDETIQVOL', 'Etiqueta de volume', 'LXD', '', '', '', 'N', 1, 0, 0, 0, 0, 0, 'Habilita a impressão da etiqueta de volume durante a venda', '', 0, '');
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('LXDTIPETIQ', 'Tipo etiqueta volume', 'LXD', '', '', '', 'N', 1, 0, 0, 0, 0, 0, 'Define o momento que será impresso a etiqueta de volume: 0 = nunca; 1 = pre-venda, 2 = Venda', '', 0, '');

CREATE TABLE  CO1 (
  CO1FECHA CHAR(5) NOT NULL,
  CO1INICIO DATETIME DEFAULT '1899-12-30 00:00:00',
  CO1FIM DATETIME DEFAULT '1899-12-30 00:00:00',
  CO1USUARIO CHAR(3) NOT NULL,
  CO1REPRES CHAR(3) NOT NULL,
  PRIMARY KEY (CO1FECHA)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO DC0 (DC0ARQUIVO,DC0NOME,DC0ACESSO,DC0NAOIMP,DC0NAOEXP,DC0CONEXAO,DC0TIPO) VALUES ('CO1', 'Fechamento de comissão', 0, 0, 0, 0, 1);
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('CO1FECHA', 'Código do fechamento', 'CO1', '', '', '', 'C', 5, 0, 0, 1, 0, 1, 'Código idenficador do fechamento de comissão', '', 0, '');
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('CO1INICIO', 'Data/Hora inicial', 'CO1', '', '', '', 'T', 8, 0, 0, 5, 0, 0, 'Data e hora em que vai contabilizar o início das vendas para o fechamento de comissão', '', 0, '');
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('CO1FIM', 'Data/Hora final', 'CO1', '', '', '', 'T', 8, 0, 0, 5, 0, 0, 'Data e hora em que vai contabilizar o fim das vendas para o fechamento de comissão', '', 0, '');
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('CO1USUARIO', 'Fechado por', 'CO1', 'DC4', 'DC4USUARIO', '', 'C', 3, 0, 0, 1, 0, 0, 'Usuário responsável pelo fechamento de comissão', 'DC4', 0, '');
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('CO1REPRES', 'Representante', 'CO1', 'CF6', 'CF6REPRES', '', 'C', 3, 0, 0, 1, 0, 0, 'Representante do fechamento de comissão', 'CF6', 0, '');

UPDATE DC1 SET DC1FORMATO = 5 WHERE DC1CAMPO IN ('CX1DATA', 'CX0ABERT', 'CX0FECHA');

CREATE TABLE  CO2 (
  CO2FECHA CHAR(5) NOT NULL,
  CO2DOC CHAR(6) NOT NULL,
  CO2TIPO CHAR(3) NOT NULL,
  CO2EMISSOR CHAR(14) NOT NULL,
  PRIMARY KEY (CO2FECHA, CO2DOC, CO2TIPO, CO2EMISSOR)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO DC0 (DC0ARQUIVO,DC0NOME,DC0ACESSO,DC0NAOIMP,DC0NAOEXP,DC0CONEXAO,DC0TIPO) VALUES ('CO2', 'Vendas comissionadas', 0, 0, 0, 0, 1);
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('CO2FECHA', 'Código do fechamento', 'CO2', 'CO1', 'CO1FECHA', '', 'C', 5, 0, 0, 1, 0, 1, 'Código idenficador do fechamento de comissão', 'CO1', 0, '');
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('CO2DOC', 'Numero do Documento', 'CO2', 'CV5', 'CV5DOC', 'CO2TIPO=CV5TIPO+CO2EMISSOR=CV5EMISSOR', 'C', 6, 0, 0, 1, 0, 2, 'Número do Documento Fiscal', '', 0, '');
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('CO2TIPO', 'Tipo de Documento', 'CO2', 'CV5', 'CV5TIPO', 'CO2EMISSOR=CV5EMISSOR+CO2DOC=CV5DOC', 'C', 3, 0, 0, 0, 0, 3, 'Tipo de Documento Fiscal', '', 0, '');
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('CO2EMISSOR', 'Emitente', 'CO2', 'CV5', 'CV5EMISSOR', 'CO2TIPO=CV5TIPO+CO2DOC=CV5DOC', 'C', 14, 0, 0, 0, 0, 4, 'Emitente do documento.', '', 0, '');


-- VIEWS ESTATÍSTICAS CAIXA

-- total de vendas (quantidade)
DROP VIEW IF EXISTS `pdv_tot_vendas`;
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW  `pdv_tot_vendas` AS select 'mdi-basket' AS `Icon`,'teal darken-2' AS `ColorIcon`,'Vendas' AS `Header`,count(0) AS `Value`,time_format(now(),'%H:%i') AS `LastUpdate` from (`vd1` join `cv5` on(((`cv5`.`CV5PEDIDO` = `vd1`.`VD1PEDIDO`) and (`cv5`.`CV5SITUA` = '') and (`cv5`.`CV5EMITIDO` = 1) and (`cv5`.`CV5ENTSAI` = 1) and (`vd1`.`VD1CONSIG` = 0))))INNER JOIN VD6 ON VD6PEDIDO = VD1PEDIDO where (date_format(`vd1`.`VD1ENTRADA`,'%Y-%m-%d') = cast(now() as date)) AND (CV5MODELO <> '55' OR (CV5MODELO = '55' AND NOT EXISTS (SELECT CV5DOC FROM CV5 WHERE CV5PEDIDO = VD1PEDIDO AND CV5EMBARQ = VD6EMBARQ AND CV5MODELO = '99'  AND CV5SITUA = '' AND CV5EMITIDO = 1 AND CV5ENTSAI = 1)));

-- total de itens vendidos (quantidade)
DROP VIEW IF EXISTS `pdv_tot_qtde_vendas`;
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW  `pdv_tot_qtde_vendas` AS select 'mdi-package' AS `Icon`, 'brown' AS `ColorIcon`, 'Produtos vendidos' AS `Header`, sum(`vd3`.`VD3QTDE`) AS `VALUE`, time_format(now(),'%H:%i') AS `LastUpdate` from ((`vd1` join `vd3` on((`vd3`.`VD3PEDIDO` = `vd1`.`VD1PEDIDO`))) INNER JOIN VD6 ON VD6PEDIDO = VD1PEDIDO join `cv5` on(((`cv5`.`CV5PEDIDO` = `vd1`.`VD1PEDIDO`) and (`cv5`.`CV5SITUA` = '') and (`cv5`.`CV5EMITIDO` = 1) and (`cv5`.`CV5ENTSAI` = 1) and (`vd1`.`VD1CONSIG` = 0)))) where (date_format(`vd1`.`VD1ENTRADA`,'%Y-%m-%d') = cast(now() as date)) AND (CV5MODELO <> '55' OR (CV5MODELO = '55' AND NOT EXISTS (SELECT CV5DOC FROM CV5 WHERE CV5PEDIDO = VD1PEDIDO AND CV5EMBARQ = VD6EMBARQ AND CV5MODELO = '99'  AND CV5SITUA = '' AND CV5EMITIDO = 1 AND CV5ENTSAI = 1))) order by value ;

-- vendas para novos cliente no dia (soma)
DROP VIEW IF EXISTS `pdv_qtde_vendas_novos_clientes`;
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW  `pdv_qtde_vendas_novos_clientes` AS  select 'mdi-account-cash' AS `Icon`,'light-blue darken-3' AS `ColorIcon`,'Vendas - Novos clientes' AS `Header`,count(`vd1`.`VD1PEDIDO`) AS `VALUE`,time_format(now(),'%H:%i') AS `LastUpdate` from (`vd1` join `cf1` on((`cf1`.`CF1CLIENTE` = `vd1`.`VD1CLIENTE`))) INNER JOIN VD6 ON VD6PEDIDO = VD1PEDIDO where ((`vd1`.`VD1CONSIG` = 0) and (date_format(`cf1`.`CF1ABERT`,'%Y-%m-%d') = cast(now() as date)) and `vd1`.`VD1PEDIDO` in (select `cv5`.`CV5PEDIDO` from `cv5` where ((`cv5`.`CV5SITUA` = '') and (`cv5`.`CV5EMITIDO` = 1) and (`cv5`.`CV5ENTSAI` = 1) AND (CV5MODELO <> '55' OR (CV5MODELO = '55' AND NOT EXISTS (SELECT CV5DOC FROM CV5 WHERE CV5PEDIDO = VD1PEDIDO AND CV5EMBARQ = VD6EMBARQ AND CV5MODELO = '99'  AND CV5SITUA = '' AND CV5EMITIDO = 1 AND CV5ENTSAI = 1))))));

-- Total de vendas (soma)
DROP VIEW IF EXISTS `pdv_valor_vendas`;
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW  `pdv_valor_vendas` AS SELECT 'mdi-currency-usd' AS Icon, 'green' AS ColorIcon,'Total de vendas' AS Header,
SUM(CV5TOTALNF) AS Value,TIME_FORMAT(NOW(), '%H:%i') AS LastUpdate  FROM (VD1 INNER JOIN CV5 ON CV5PEDIDO = VD1PEDIDO AND CV5SITUA = '' AND CV5EMITIDO = 1 AND CV5ENTSAI=1 AND VD1CONSIG = 0)
INNER JOIN VD6 ON VD6PEDIDO = VD1PEDIDO   WHERE (date_format(`cv5`.`cv5emissao`,'%Y-%m-%d') = cast(now() as date))
AND (CV5MODELO <> '55' OR (CV5MODELO = '55' AND NOT EXISTS (SELECT CV5DOC FROM CV5 WHERE CV5PEDIDO = VD1PEDIDO AND CV5EMBARQ = VD6EMBARQ AND CV5MODELO = '99'  AND CV5SITUA = '' AND CV5EMITIDO = 1 AND CV5ENTSAI = 1)));

CREATE INDEX FISCALDOCUMENT ON CO2(CO2DOC,CO2TIPO,CO2EMISSOR);

ALTER TABLE VDF ADD COLUMN VDFVOLUME CHAR(6) DEFAULT NULL;
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('VDFVOLUME', 'Número do Volume', 'VDF', 'VD7', 'VD7VOLUME', '', 'C', 6, 0, 0, 1, 0, 1, 'Número do volume.', '', 0, '');

ALTER TABLE LXD ADD COLUMN LXDNFBOL DECIMAL(1,0) DEFAULT 0;
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('LXDNFBOL', 'NF + Boleto', 'LXD', '', '', '', 'N', 1, 0, 0, 0, 1, 0, 'Habilita emissão de boletos durante a venda.', '', 0, '');

DELETE FROM PD7;

INSERT INTO PD7 (PD7EMISSOR,PD7AGENTE,PD7VALOR,PD7LINHA1,PD7LINHA2,PD7NOMINAL,PD7CIDADE,PD7DIA,PD7MES,PD7ANO,PD7BOMPARA)  VALUES ((SELECT PD6EMISSOR FROM PD6),'001','754,228','443,244','380,268','380,281','584,304','680,304','718,304','821,304','754,380');
INSERT INTO PD7 (PD7EMISSOR,PD7AGENTE,PD7VALOR,PD7LINHA1,PD7LINHA2,PD7NOMINAL,PD7CIDADE,PD7DIA,PD7MES,PD7ANO,PD7BOMPARA)  VALUES ((SELECT PD6EMISSOR FROM PD6),'033','754,225','440,243','380,268','380,280','584,300','685,300','718,300','821,300','754,380');
INSERT INTO PD7 (PD7EMISSOR,PD7AGENTE,PD7VALOR,PD7LINHA1,PD7LINHA2,PD7NOMINAL,PD7CIDADE,PD7DIA,PD7MES,PD7ANO,PD7BOMPARA)  VALUES ((SELECT PD6EMISSOR FROM PD6),'041','754,223','440,242','380,267','380,280','584,300','705,300','735,300','822,300','754,380');
INSERT INTO PD7 (PD7EMISSOR,PD7AGENTE,PD7VALOR,PD7LINHA1,PD7LINHA2,PD7NOMINAL,PD7CIDADE,PD7DIA,PD7MES,PD7ANO,PD7BOMPARA)  VALUES ((SELECT PD6EMISSOR FROM PD6),'104','754,215','440,234','380,258','380,273','573,300','672,300','718,300','820,300','754,392');
INSERT INTO PD7 (PD7EMISSOR,PD7AGENTE,PD7VALOR,PD7LINHA1,PD7LINHA2,PD7NOMINAL,PD7CIDADE,PD7DIA,PD7MES,PD7ANO,PD7BOMPARA)  VALUES ((SELECT PD6EMISSOR FROM PD6),'237','750,217','440,241','380,263','380,278','575,298','667,298','716,298','819,298','754,380');
INSERT INTO PD7 (PD7EMISSOR,PD7AGENTE,PD7VALOR,PD7LINHA1,PD7LINHA2,PD7NOMINAL,PD7CIDADE,PD7DIA,PD7MES,PD7ANO,PD7BOMPARA)  VALUES ((SELECT PD6EMISSOR FROM PD6),'341','754,215','440,231','380,250','380,265','580,286','678,286','718,286','817,286','754,380');
INSERT INTO PD7 (PD7EMISSOR,PD7AGENTE,PD7VALOR,PD7LINHA1,PD7LINHA2,PD7NOMINAL,PD7CIDADE,PD7DIA,PD7MES,PD7ANO,PD7BOMPARA)  VALUES ((SELECT PD6EMISSOR FROM PD6),'748','754,220','440,240','380,262','380,275','584,298','672,298','718,298','821,298','754,385');

UPDATE DC9 SET DC9IMPRES = 4 WHERE DC9RELAT IN ('322', '321', '282');

CREATE TABLE PD3 (
  PD3VIEW1 DECIMAL(1,0) DEFAULT 1,
  PD3VIEW2 DECIMAL(1,0) DEFAULT 1,
  PD3VIEW3 DECIMAL(1,0) DEFAULT 1,
  PD3VIEW4 DECIMAL(1,0) DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('PD3VIEW1', 'View 1 do caixa', 'PD3', '', '', '', 'N', 1, 0, 0, 0, 0, 0, 'View 1 do caixa para o sistema PDV', '', 0, '');
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('PD3VIEW2', 'View 2 do caixa', 'PD3', '', '', '', 'N', 1, 0, 0, 0, 0, 0, 'View 2 do caixa para o sistema PDV', '', 0, '');
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('PD3VIEW3', 'View 3 do caixa', 'PD3', '', '', '', 'N', 1, 0, 0, 0, 0, 0, 'View 3 do caixa para o sistema PDV', '', 0, '');
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('PD3VIEW4', 'View 4 do caixa', 'PD3', '', '', '', 'N', 1, 0, 0, 0, 0, 0, 'View 4 do caixa para o sistema PDV', '', 0, '');
UPDATE DC0 SET DC0NOME = 'Principal Caixa' WHERE DC0ARQUIVO = 'PD3';

UPDATE DC9 SET DC9IMPRES = 4 WHERE DC9RELAT IN ('323');

ALTER TABLE CO1 MODIFY COLUMN CO1REPRES CHAR(4);
UPDATE DC1 SET DC1TAMANHO = 4 WHERE DC1CAMPO = 'CO1REPRES';

UPDATE DC1 SET DC1EDICAO = 3 WHERE DC1CAMPO = 'FNLEMISSOR';

ALTER TABLE LX8 ADD COLUMN LX8INFO TEXT;
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('LX8INFO', 'Informações do log', 'LX8', '', '', '', 'C', 254, 0, 0, 0, 0, 0, 'Dados adicionais para informações de log', '', 0, '');

UPDATE LX0 SET LX0LOGS = 1;

UPDATE DC9 SET DC9ARQUIVO = 'CX0' WHERE DC9RELAT = '322';

CREATE TABLE  VE0 (
  VE0VEND CHAR(3) NOT NULL,
  VE0CLIENTE CHAR(14) NOT NULL,
  VE0ATIVO DECIMAL(1,0) DEFAULT 0,
  VE0COMIS decimal(5,2) DEFAULT 0.00,
  PRIMARY KEY (VE0VEND)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO DC0 (DC0ARQUIVO,DC0NOME,DC0ACESSO,DC0NAOIMP,DC0NAOEXP,DC0CONEXAO,DC0TIPO) VALUES ('VE0', 'Vendedores', 0, 0, 0, 0, 1);
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('VE0VEND', 'Código', 'VE0', '', '', '', 'C', 3, 0, 0, 1, 0, 1, 'Código idenficador do vendedor', '', 0, '');
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('VE0CLIENTE', 'Cnpj / Cpf', 'VE0', 'CF1', 'CF1CLIENTE', '', 'C', 14, 0, 1, 0, 1, 0, 'Cnpj ou Cpf cadastrado em clientes / fornecedores.', 'CF1', 0, '');
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('VE0ATIVO', 'Ativo', 'VE0', '', '', '', 'N', 1, 0, 0, 0, 0, 0, 'Indica se o vendedor está ativo ou não', '', 0, '');
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('VE0COMIS', 'Percentual de Comissão', 'VE0', '', '', '', 'N', 5, 2, 0, 0, 1, 0, 'Percentual de comissão.', '', 0, '');

ALTER TABLE VD1 ADD COLUMN VD1VEND CHAR(3) DEFAULT '';
ALTER TABLE VD1 ADD COLUMN VD1COMVEN DECIMAL(5,2) DEFAULT 0.00;
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('VD1VEND', 'Vendedor', 'VD1', 'VE0', 'VE0VEND', '', 'C', 3, 0, 0, 1, 1, 0, 'Código idenficador do vendedor do pedido.', 'VE0', 0, '');
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('VD1COMVEN', 'Comissão do vendedor', 'VD1', '', '', '', 'N', 5, 2, 0, 0, 1, 0, 'Percentual de comissão do vendedor para o pedido.', '', 0, '');

CREATE TABLE  VE1 (
  VE1TIPO CHAR(2) NOT NULL,
  VE1NOME  CHAR(20) NOT NULL,
  PRIMARY KEY (VE1TIPO)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO DC0 (DC0ARQUIVO,DC0NOME,DC0ACESSO,DC0NAOIMP,DC0NAOEXP,DC0CONEXAO,DC0TIPO) VALUES ('VE1', 'Tipos de Meta', 0, 0, 0, 0, 1);
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('VE1TIPO', 'Código', 'VE1', '', '', '', 'C', 2, 0, 0, 0, 0, 1, 'Código idenficador do tipo de meta', '', 0, '');
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('VE1NOME', 'Nome', 'VE1', '', '', '', 'C', 20, 0, 0, 0, 0, 0, 'Nome identificador do tipo de meta', '', 0, '');


CREATE TABLE  VE2 (
  VE2META CHAR(5) NOT NULL,
  VE2MES  DATETIME DEFAULT '1899-12-30 00:00:00',
  VE2VALOR DECIMAL(9,2) DEFAULT 0.00,
  VE2TIPO CHAR(2) NOT NULL,
  PRIMARY KEY (VE2META)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE INDEX TPMETA_MES ON VE2(VE2MES,VE2TIPO);

INSERT INTO DC0 (DC0ARQUIVO,DC0NOME,DC0ACESSO,DC0NAOIMP,DC0NAOEXP,DC0CONEXAO,DC0TIPO) VALUES ('VE2', 'Metas', 0, 0, 0, 0, 1);
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('VE2META', 'Código', 'VE2', '', '', '', 'C', 5, 0, 0, 1, 0, 1, 'Código idenficador da meta', '', 0, '');
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('VE2MES', 'Mês/Ano', 'VE2', '', '', '', 'T', 8, 0, 0, 5, 0, 0, 'Mês e ano da meta', '', 0, '');
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('VE2VALOR', 'Valor', 'VE2', '', '', '', 'N', 9, 2, 0, 0, 1, 0, 'Valor da meta a ser batida para a loja.', '', 0, '');
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('VE2TIPO', 'Tipo', 'VE2', 'VE1', 'VE1TIPO', '', 'C', 2, 0, 0, 0, 0, 0, 'Tipo da meta a ser batida.', 'VE1', 0, '');

UPDATE DC9 SET DC9ARQUIVO = 'VD1' WHERE DC9RELAT = '324';
UPDATE DC9 SET DC9NOME = 'Demonstrativo de caixa' WHERE DC9RELAT = '322';

-- rodar apenas quando o cliente usar EAN na venda
-- UPDATE CV3 SET CV3EAN = 1 WHERE CV3OPERCOM IN (SELECT PD2OPERCOM FROM PD2 WHERE PD2TIPOOPE IN (1,4));

ALTER TABLE VDX ADD COLUMN VDXQTDEENT DECIMAL(4,0) DEFAULT 0;
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('VDXQTDEENT', 'Qtde entrada', 'VDX', '', '', '', 'N', 4, 0, 1, 0, 1, 0, 'Quantidade devolvida por entrada', '', 0, '');

UPDATE DC1 SET DC1AJUDA = 'Quantidade devolvida' WHERE DC1CAMPO = 'VDXQTDE';

ALTER TABLE PD6 ADD COLUMN PD6ROTACAO DECIMAL(4) DEFAULT 0;
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('PD6ROTACAO', 'Rotação', 'PD6', '', '', '', 'N', 4, 0, 0, 0, 1, 0, 'Rotação em que será impresso o documento PDF do cheque.', '', 0, '');

UPDATE DC1 SET DC1NULO = 1 WHERE DC1CAMPO IN ('LXDTIPETIQ', 'LXDETIQVOL', 'VD1FRETE', 'VDEFECHA');

-- alter 567
UPDATE DC9 SET DC9ARQUIVO = 'VE0' WHERE DC9RELAT = '327';

ALTER TABLE LX8 MODIFY COLUMN LX8INFO MEDIUMTEXT DEFAULT NULL;

-- alter 568
ALTER TABLE LXD ADD COLUMN LXDABAOUTR DECIMAL(1,0) DEFAULT 0;
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('LXDABAOUTR', 'Usar aba Outros NFE', 'LXD', '', '', '', 'N', 1, 0, 0, 0, 1, 0, 'Habilita aba Outros NFE na tela de venda do PDV.', '', 0, '');

# PITUCHINHUS
ALTER TABLE OF3 ADD COLUMN OF3CODEXT CHAR(15) DEFAULT '';
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('OF3CODEXT', 'Cod sisplan', 'OF3', '', '', '', 'C', 15, 0, 0, 1, 0, 0, 'Código da peça no Sisplan.', '', 0, '');

-- alter 569
ALTER TABLE VDZ ADD COLUMN VDZVOLUME CHAR(6) DEFAULT '';
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('VDZVOLUME', 'Número do Volume', 'VDZ', 'VD7', 'VD7VOLUME ', '', 'C', 6, 0, 0, 1, 0, 0, 'Número do Volume do pedido consginado acertado', '', 0, '');
UPDATE DC1 SET DC1AJUDA = 'Número do Volume do pedido consginado acertado' WHERE DC1CAMPO = 'VDFVOLUME';

ALTER TABLE VDZ DROP PRIMARY KEY;
ALTER TABLE VDZ ADD CONSTRAINT PRIMARY KEY (VDZDOC, VDZPECA, VDZPRODUTO, VDZOPCAO, VDZTAMANHO, VDZVOLUME);
CREATE INDEX VDZVOLUME ON VDZ(VDZVOLUME);

ALTER TABLE VDV DROP PRIMARY KEY;
ALTER TABLE VDV ADD CONSTRAINT PRIMARY KEY (VDVVOLUME, VDVPECA, VDVPRODUTO, VDVOPCAO, VDVTAMANHO, VDVPRECO);

UPDATE DC9 SET DC9LAYOUT = 'F191' WHERE DC9RELAT = '191';
UPDATE DC9 SET DC9ARQUIVO = 'CX0' WHERE DC9RELAT = '191';
UPDATE DC9 SET DC9ARQUIVO = 'CX0' WHERE DC9RELAT = '329';

ALTER TABLE LXD ADD COLUMN LXDDOCCRE CHAR(3) DEFAULT '';
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('LXDDOCCRE', 'Documento de crédito', 'LXD', 'CV1', 'CV1DOCFIS', '', 'C', 3, 0, 0, 1, 1, 0, 'Documento fiscal para créditos de clientes', 'CV1', 0, '');

-- alter569003
ALTER TABLE LXD ADD COLUMN LXDDESCBRU DECIMAL(1) DEFAULT 0;
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('LXDDESCBRU', 'Desconto por valor bruto', 'LXD', '', '', '', 'N', 1, 0, 0, 0, 1, 0, 'Habilita calcular o valor do desconto na venda pelo valor bruto do carrinho', '', 0, '');

--ALTER572

-- Total de vendas (soma)
DROP VIEW IF EXISTS `pdv_valor_vendas`;
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW  `pdv_valor_vendas` AS SELECT 'mdi-currency-usd' AS Icon, 'green' AS ColorIcon,'Total de vendas' AS Header,
SUM(CV8VALOR) AS Value,TIME_FORMAT(NOW(), '%H:%i') AS LastUpdate
FROM (VD1 INNER JOIN CV5 ON CV5PEDIDO = VD1PEDIDO AND CV5SITUA = '' AND CV5EMITIDO = 1 AND CV5ENTSAI=1 AND VD1CONSIG = 0 INNER JOIN LX0 ON LX0CLIENTE = CV5EMISSOR INNER JOIN CV8 ON CV8DOC = CV5DOC AND CV8TIPO = CV5TIPO AND CV8EMISSOR = CV5EMISSOR)
INNER JOIN VD6 ON VD6PEDIDO = VD1PEDIDO
WHERE date_format(cv5emissao,'%Y-%m-%d') = cast(now() as date)
AND ((CV5MODELO <> '55' AND CV5MODELO <> '65') OR ((CV5MODELO = '55' OR CV5MODELO = '65') AND NOT EXISTS (SELECT CV5.CV5DOC FROM CV5 WHERE  CV5.CV5MODELO = '99' AND CV5PEDIDO=VD1PEDIDO AND CV5EMBARQ=VD6EMBARQ AND CV5.CV5SITUA = '' AND CV5.CV5EMITIDO = 1 AND CV5.CV5ENTSAI = 1)));

-- total de vendas (quantidade)
DROP VIEW IF EXISTS `pdv_tot_vendas`;
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW  `pdv_tot_vendas` AS SELECT 'mdi-basket' AS Icon,'teal darken-2' AS ColorIcon,'Vendas' AS Header, count(0) AS Value, time_format(now(),'%H:%i') AS LastUpdate
FROM (VD1 JOIN CV5 ON CV5PEDIDO = VD1PEDIDO AND CV5SITUA = '' AND CV5EMITIDO = 1 AND CV5ENTSAI = 1 AND VD1CONSIG = 0 INNER JOIN LX0 ON LX0CLIENTE = CV5EMISSOR)
INNER JOIN VD6 ON VD6PEDIDO = VD1PEDIDO
WHERE DATE_FORMAT(VD1ENTRADA,'%Y-%m-%d') = CAST(NOW() AS DATE)
AND ((CV5MODELO <> '55' AND CV5MODELO <> '65') OR ((CV5MODELO = '55' OR CV5MODELO = '65') AND NOT EXISTS (SELECT CV5.CV5DOC FROM CV5 WHERE  CV5.CV5MODELO = '99' AND CV5PEDIDO=VD1PEDIDO AND CV5EMBARQ=VD6EMBARQ AND CV5.CV5SITUA = '' AND CV5.CV5EMITIDO = 1 AND CV5.CV5ENTSAI = 1)));

-- total de itens vendidos (quantidade)
DROP VIEW IF EXISTS `pdv_tot_qtde_vendas`;
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW  `pdv_tot_qtde_vendas` AS SELECT 'mdi-package' AS Icon, 'brown' AS ColorIcon, 'Produtos vendidos' AS Header, ROUND(SUM(CV7QTDE),0) AS VALUE, TIME_FORMAT(NOW(),'%H:%i') AS LastUpdate
FROM (VD1 INNER JOIN VD6 ON VD6PEDIDO = VD1PEDIDO INNER JOIN CV5 ON CV5PEDIDO = VD1PEDIDO AND CV5EMBARQ = VD6EMBARQ AND CV5SITUA = '' AND CV5EMITIDO = 1 AND CV5ENTSAI = 1 AND VD1CONSIG = 0 INNER JOIN LX0 ON LX0CLIENTE = CV5EMISSOR INNER JOIN CV7 ON CV7DOC = CV5DOC AND CV7TIPO = CV5TIPO AND CV7EMISSOR = CV5EMISSOR)
WHERE DATE_FORMAT(VD1ENTRADA,'%Y-%m-%d') = CAST(NOW() AS DATE)
AND ((CV5MODELO <> '55' AND CV5MODELO <> '65') OR ((CV5MODELO = '55' OR CV5MODELO = '65') AND NOT EXISTS (SELECT CV5.CV5DOC FROM CV5 WHERE  CV5.CV5MODELO = '99' AND CV5PEDIDO=VD1PEDIDO AND CV5EMBARQ=VD6EMBARQ AND CV5.CV5SITUA = '' AND CV5.CV5EMITIDO = 1 AND CV5.CV5ENTSAI = 1)));

-- vendas para novos cliente no dia (soma)
DROP VIEW IF EXISTS `pdv_qtde_vendas_novos_clientes`;
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW  `pdv_qtde_vendas_novos_clientes` AS SELECT 'mdi-account-cash' AS Icon,'light-blue darken-3' AS ColorIcon,'Vendas - Novos clientes' AS Header,count(VD1PEDIDO) AS VALUE, TIME_FORMAT(NOW(),'%H:%i') AS LastUpdate
FROM (VD1 INNER JOIN CF1 ON CF1CLIENTE = VD1CLIENTE INNER JOIN VD6 ON VD6PEDIDO = VD1PEDIDO)
WHERE VD1CONSIG = 0
AND DATE_FORMAT(CF1ABERT,'%Y-%m-%d') = CAST(NOW() AS DATE)
AND VD1PEDIDO IN (SELECT CV5PEDIDO FROM CV5 WHERE CV5SITUA = '' AND CV5EMITIDO = 1 AND CV5ENTSAI = 1 AND ((CV5MODELO <> '55' AND CV5MODELO <> '65') OR ((CV5MODELO = '55' OR CV5MODELO = '65') AND NOT EXISTS (SELECT CV5.CV5DOC FROM CV5 WHERE  CV5.CV5MODELO = '99' AND CV5PEDIDO=VD1PEDIDO AND CV5EMBARQ=VD6EMBARQ AND CV5.CV5SITUA = '' AND CV5.CV5EMITIDO = 1 AND CV5.CV5ENTSAI = 1))));

UPDATE DC9 SET DC9ARQUIVO = 'OF3' WHERE DC9RELAT = '112';
UPDATE DC9 SET DC9ARQUIVO = 'EAN' WHERE DC9RELAT = '271';

ALTER TABLE LXD ADD COLUMN LXDORYXBI CHAR(254) DEFAULT '';
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('LXDORYXBI', 'URL Oryx BI', 'LXD', '', '', '', 'C', 254, 0, 0, 0, 1, 0, 'Link para acesso ao Oryx BI', '', 0, '');

-- ALTER 5.7.5000
ALTER TABLE LXD ADD COLUMN LXDCHEQUE DECIMAL(1,0) DEFAULT 0;
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('LXDCHEQUE', 'Cheque obrigatório', 'LXD', '', '', '', 'N', 1, 0, 0, 0, 1, 0, 'Obriga informar o número do cheque e agente financeiro nas parcelas da venda', '', 0, '');

-- ALTER 5.7.7000
ALTER TABLE CO1 ADD COLUMN CO1ABERT DATETIME DEFAULT '1899-12-30 00:00:00';
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('CO1ABERT', 'Data geração', 'CO1', '', '', '', 'T', 8, 0, 0, 0, 0, 0, 'Data e hora em que o fechamento de comissão foi realizado', '', 0, '');
ALTER TABLE LXD ADD COLUMN LXDSALVAR DECIMAL(1,0) DEFAULT 0;
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('LXDSALVAR', 'Habilitar salvar', 'LXD', '', '', '', 'N', 1, 0, 0, 0, 1, 0, 'Habilitar salvar o pedido na tela de venda', '', 0, '');
ALTER TABLE LXD ADD COLUMN LXDPRINREL DECIMAL(1,0) DEFAULT 0;
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('LXDPRINREL', 'Imprimir relatório extra', 'LXD', '', '', '', 'N', 1, 0, 0, 0, 1, 0, 'Habilitar a impressão de um relatório extra durante emissão de documentos fiscais na venda', '', 0, '');
ALTER TABLE LXD ADD COLUMN LXDRELAT CHAR(3) DEFAULT '';
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('LXDRELAT', 'Relatório extra', 'LXD', 'DC9', 'DC9RELAT', '', 'C', 3, 0, 0, 1, 1, 0, 'Código do relatório extra a ser impresso durante a emissão de documentos fiscais na venda', 'DC9', 0, '');

-- ALTER 5.7.8000
CREATE TABLE PD8 (
  PD8CODIGO char(1) NOT NULL,
  PD8NOME CHAR(20) DEFAULT ' ',
  PD8BASEURL CHAR(254) DEFAULT ' ',
  PD8TOKEN CHAR(254) DEFAULT ' ',
  PD8TIPO DECIMAL(1) DEFAULT 0,
  PD8FLAG1 DECIMAL(1) DEFAULT 0,
  PD8FLAG2 DECIMAL(1) DEFAULT 0,
  PD8FLAG3 DECIMAL(1) DEFAULT 0,
  PRIMARY KEY (PD8CODIGO)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO DC0 (DC0ARQUIVO,DC0NOME,DC0ACESSO,DC0NAOIMP,DC0NAOEXP,DC0CONEXAO,DC0TIPO)  values ('PD8','Param Integração Guias',0,0,0,1,0);

Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('PD8CODIGO', 'Código', 'PD8', '', '', '', 'C', 1, 0, 0, 1, 0, 1, 'Código exclusivamente para chave', '', 1, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('PD8NOME', 'Nome', 'PD8', '', '', '', 'C', 20, 0, 0, 0, 0, 0, 'Nome da integração', '', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('PD8BASEURL', 'Url microserviço', 'PD8', '', '', '', 'C', 254, 0, 0, 0, 1, 0, 'Url base dos microserviços', '', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('PD8TOKEN', 'Token', 'PD8', '', '', '', 'C', 254, 0, 0, 0, 1, 0, 'Token de autenticação com o microserviço', '', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('PD8TIPO', 'Tipo', 'PD8', '', '', '', 'N', 1, 0, 0, 0, 0, 0, 'Tipo de Integração de Guias: 1 - ACECORS', '', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('PD8FLAG1', 'Parâmetro 1', 'PD8', '', '', '', 'N', 1, 0, 0, 0, 1, 0, 'Campo para filtro na consulta de guias: Apenas com restrição - ACECORS', '', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('PD8FLAG2', 'Parâmetro 2', 'PD8', '', '', '', 'N', 1, 0, 0, 0, 1, 0, 'Campo para filtro na consulta de guias: Apenas com Serasa - ACECORS', '', 0, '');
Insert into DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO)  values ('PD8FLAG3', 'Parâmetro 3', 'PD8', '', '', '', 'N', 1, 0, 0, 0, 1, 0, 'Campo para filtro na consulta de guias: Apenas com observação - ACECORS', '', 0, '');

ALTER TABLE LXD ADD COLUMN LXDORYXWHA DECIMAL(1,0) DEFAULT 0;
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('LXDORYXWHA', 'Integração Oryx WhatsApp', 'LXD', '', '', '', 'N', 1, 0, 0, 0, 1, 0, 'Habilitar a integração com o sistema Oryx WhatsApp', '', 0, '');

INSERT INTO DC0 (DC0ARQUIVO,DC0NOME,DC0ACESSO,DC0NAOIMP,DC0NAOEXP,DC0CONEXAO,DC0TIPO)  values ('PDC','Consul Integração Guias',0,0,0,1,0);

-- ALTER 5.7.9000

ALTER TABLE LXE ADD COLUMN LXEAPICEP CHAR(100) DEFAULT '';
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('LXEAPICEP', 'API CEP', 'LXE', '', '', '', 'C', 100, 0, 0, 0, 0, 0, 'Link para consulta de cep', '', 0, '');

ALTER TABLE LXD ADD COLUMN LXDPRECMOD DECIMAL(1,0) DEFAULT 0;
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('LXDPRECMOD', 'Consulta detalhada', 'LXD', '', '', '', 'N', 1, 0, 0, 0, 1, 0, 'Habilitar a consulta de preço detalhada na tela de Consulta Preço', '', 0, '');
ALTER TABLE LXD ADD COLUMN LXDPRECEST DECIMAL(1,0) DEFAULT 0;
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('LXDPRECEST', 'Mostrar estoque', 'LXD', '', '', '', 'N', 1, 0, 0, 0, 1, 0, 'Habilitar a visualização do estoque na tela de Consulta Preço', '', 0, '');

ALTER TABLE LXD ADD COLUMN LXDPRECLIS CHAR(100) DEFAULT '';
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('LXDPRECLIS', 'Listas de preço', 'LXD', '', '', '', 'C', 100, 0, 0, 0, 0, 0, 'Listas de preço para cálculo na tela de Consulta Preço', '', 0, '');

ALTER TABLE TECDATASOFT MODIFY COLUMN CV7SUBTOT DECIMAL(9,2) DEFAULT 0;

UPDATE LXE SET LXEAPICEP = 'https://viacep.com.br/ws';

-- ALTER 5.7.9001
ALTER TABLE LXE ADD COLUMN LXEATUALIZ CHAR(50) DEFAULT '';
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('LXEATUALIZ', 'Caminho atualizar', 'LXE', '', '', '', 'C', 50, 0, 0, 0, 1, 0, 'Caminho no qual se encontra o programa para atualizar o estoque das filiais', '', 0, '');

CREATE INDEX VD6DOCCONF ON VD6(VD6DOCCONF);

ALTER TABLE LX3 ADD COLUMN LX3CFVLMAX DECIMAL(12,2) DEFAULT 0;
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('LX3CFVLMAX', 'Valor máx. CF n identif.', 'LX3', '', '', '', 'N', 12, 2, 0, 0, 1, 0, 'Valor máximo que o sistema não exigirá a identificação do consumidor final para emissão de CF', '', 0, '');

ALTER TABLE LXD ADD COLUMN LXDESTVEN DECIMAL(1,0) DEFAULT 0;
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('LXDESTVEN', 'Mostrar estoque na venda', 'LXD', '', '', '', 'N', 1, 0, 0, 0, 1, 0, 'Habilita visualizar o estoque dos produtos na tela de venda', '', 0, '');
ALTER TABLE LXD ADD COLUMN LXDESTNEG DECIMAL(1,0) DEFAULT 0;
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('LXDESTNEG', 'Alertar estoque negativo', 'LXD', '', '', '', 'N', 1, 0, 0, 0, 1, 0, 'Habilita alerta de estoque negativo na leitura de peças na tela de venda', '', 0, '');
ALTER TABLE LXD ADD COLUMN LXDESTBLOQ DECIMAL(1,0) DEFAULT 0;
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('LXDESTBLOQ', 'Controlar saída estoque', 'LXD', '', '', '', 'N', 1, 0, 0, 0, 1, 0, 'Habilita o controle de estoque durante as vendas, bloqueando em caso de estoque negativo', '', 0, '');

ALTER TABLE LXD ADD COLUMN LXDCOMADEV DECIMAL(3,0) DEFAULT 0;
INSERT INTO DC1 (DC1CAMPO,DC1NOME,DC1ARQUIVO,DC1ARQPAI,DC1CAMPAI,DC1ASCEND,DC1TIPO,DC1TAMANHO,DC1DECIMAL,DC1ESPACO,DC1FORMATO,DC1NULO,DC1CHAVE,DC1AJUDA,DC1ZOOM,DC1EDICAO,DC1ULTIMO) VALUES ('LXDCOMADEV', '% máximo devolução', 'LXD', '', '', '', 'N', 3, 0, 0, 0, 1, 0, 'Parâmetro para bloqueio percentual máximo (em valor) de devolução de peças em consignado', '', 0, '');