//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimplesTI
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Name="server.SimplesTI_SMBPortType", Namespace="urn:server.SimplesTI_SMB", ConfigurationName="SimplesTI.serverSimplesTI_SMBPortType")]
    public interface serverSimplesTI_SMBPortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:server.testa_conexao#testa_conexao", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<SimplesTI.testa_conexaoResponse> testa_conexaoAsync(SimplesTI.testa_conexaoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:server.retorna_dados_clientes#retorna_dados_clientes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<SimplesTI.retorna_dados_clientesResponse> retorna_dados_clientesAsync(SimplesTI.retorna_dados_clientesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:server.registra_venda_dinheiro_cartao#registra_venda_dinheiro_cartao", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<SimplesTI.registra_venda_dinheiro_cartaoResponse> registra_venda_dinheiro_cartaoAsync(SimplesTI.registra_venda_dinheiro_cartaoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:server.registra_venda_cheque#registra_venda_cheque", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<SimplesTI.registra_venda_chequeResponse> registra_venda_chequeAsync(SimplesTI.registra_venda_chequeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:server.retorna_dados_guias#retorna_dados_guias", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<SimplesTI.retorna_dados_guiasResponse> retorna_dados_guiasAsync(SimplesTI.retorna_dados_guiasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:server.retorna_cidades#retorna_cidades", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<SimplesTI.retorna_cidadesResponse> retorna_cidadesAsync(SimplesTI.retorna_cidadesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:server.retorna_endereco_completo#retorna_endereco_completo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<SimplesTI.retorna_endereco_completoResponse> retorna_endereco_completoAsync(SimplesTI.retorna_endereco_completoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:server.retorna_tipos_pagamentos#retorna_tipos_pagamentos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<SimplesTI.retorna_tipos_pagamentosResponse> retorna_tipos_pagamentosAsync(SimplesTI.retorna_tipos_pagamentosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:server.retorna_lojistas#retorna_lojistas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<SimplesTI.retorna_lojistasResponse> retorna_lojistasAsync(SimplesTI.retorna_lojistasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:server.registra_cliente#registra_cliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<SimplesTI.registra_clienteResponse> registra_clienteAsync(SimplesTI.registra_clienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:server.registra_venda_cheque#registra_venda_cheque", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<SimplesTI.registra_venda_geralResponse> registra_venda_geralAsync(SimplesTI.registra_venda_geralRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:server.AdocaoLimites#AdocaoLimites", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<SimplesTI.AdocaoLimitesResponse> AdocaoLimitesAsync(SimplesTI.AdocaoLimitesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="testa_conexao", WrapperNamespace="urn:server.testa_conexao", IsWrapped=true)]
    public partial class testa_conexaoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string login_sistema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string senha_sistema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string cd_lojista;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string senha_lojista;
        
        public testa_conexaoRequest()
        {
        }
        
        public testa_conexaoRequest(string login_sistema, string senha_sistema, string cd_lojista, string senha_lojista)
        {
            this.login_sistema = login_sistema;
            this.senha_sistema = senha_sistema;
            this.cd_lojista = cd_lojista;
            this.senha_lojista = senha_lojista;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="testa_conexaoResponse", WrapperNamespace="urn:server.testa_conexao", IsWrapped=true)]
    public partial class testa_conexaoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public testa_conexaoResponse()
        {
        }
        
        public testa_conexaoResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retorna_dados_clientes", WrapperNamespace="urn:server.retorna_dados_clientes", IsWrapped=true)]
    public partial class retorna_dados_clientesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string login_sistema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string senha_sistema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string cd_lojista;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string senha_lojista;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string cd_cartao_cliente;
        
        public retorna_dados_clientesRequest()
        {
        }
        
        public retorna_dados_clientesRequest(string login_sistema, string senha_sistema, string cd_lojista, string senha_lojista, string cd_cartao_cliente)
        {
            this.login_sistema = login_sistema;
            this.senha_sistema = senha_sistema;
            this.cd_lojista = cd_lojista;
            this.senha_lojista = senha_lojista;
            this.cd_cartao_cliente = cd_cartao_cliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retorna_dados_clientesResponse", WrapperNamespace="urn:server.retorna_dados_clientes", IsWrapped=true)]
    public partial class retorna_dados_clientesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public retorna_dados_clientesResponse()
        {
        }
        
        public retorna_dados_clientesResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registra_venda_dinheiro_cartao", WrapperNamespace="urn:server.registra_venda_dinheiro_cartao", IsWrapped=true)]
    public partial class registra_venda_dinheiro_cartaoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string login_sistema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string senha_sistema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string cd_lojista;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string senha_lojista;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string cd_cartao_cliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string tipo_pagamento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string data_venda;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string qt_parcelas;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public string pparcelas_xml;
        
        public registra_venda_dinheiro_cartaoRequest()
        {
        }
        
        public registra_venda_dinheiro_cartaoRequest(string login_sistema, string senha_sistema, string cd_lojista, string senha_lojista, string cd_cartao_cliente, string tipo_pagamento, string data_venda, string qt_parcelas, string pparcelas_xml)
        {
            this.login_sistema = login_sistema;
            this.senha_sistema = senha_sistema;
            this.cd_lojista = cd_lojista;
            this.senha_lojista = senha_lojista;
            this.cd_cartao_cliente = cd_cartao_cliente;
            this.tipo_pagamento = tipo_pagamento;
            this.data_venda = data_venda;
            this.qt_parcelas = qt_parcelas;
            this.pparcelas_xml = pparcelas_xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registra_venda_dinheiro_cartaoResponse", WrapperNamespace="urn:server.registra_venda_dinheiro_cartao", IsWrapped=true)]
    public partial class registra_venda_dinheiro_cartaoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public registra_venda_dinheiro_cartaoResponse()
        {
        }
        
        public registra_venda_dinheiro_cartaoResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registra_venda_cheque", WrapperNamespace="urn:server.registra_venda_cheque", IsWrapped=true)]
    public partial class registra_venda_chequeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string login_sistema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string senha_sistema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string cd_lojista;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string senha_lojista;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string cd_cartao_cliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string tipo_pagamento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string data_venda;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string qt_cheques;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public string pcheques_xml;
        
        public registra_venda_chequeRequest()
        {
        }
        
        public registra_venda_chequeRequest(string login_sistema, string senha_sistema, string cd_lojista, string senha_lojista, string cd_cartao_cliente, string tipo_pagamento, string data_venda, string qt_cheques, string pcheques_xml)
        {
            this.login_sistema = login_sistema;
            this.senha_sistema = senha_sistema;
            this.cd_lojista = cd_lojista;
            this.senha_lojista = senha_lojista;
            this.cd_cartao_cliente = cd_cartao_cliente;
            this.tipo_pagamento = tipo_pagamento;
            this.data_venda = data_venda;
            this.qt_cheques = qt_cheques;
            this.pcheques_xml = pcheques_xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registra_venda_chequeResponse", WrapperNamespace="urn:server.registra_venda_cheque", IsWrapped=true)]
    public partial class registra_venda_chequeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public registra_venda_chequeResponse()
        {
        }
        
        public registra_venda_chequeResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retorna_dados_guias", WrapperNamespace="urn:server.retorna_dados_guias", IsWrapped=true)]
    public partial class retorna_dados_guiasRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string login_sistema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string senha_sistema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string cd_lojista;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string senha_lojista;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string cd_guia;
        
        public retorna_dados_guiasRequest()
        {
        }
        
        public retorna_dados_guiasRequest(string login_sistema, string senha_sistema, string cd_lojista, string senha_lojista, string cd_guia)
        {
            this.login_sistema = login_sistema;
            this.senha_sistema = senha_sistema;
            this.cd_lojista = cd_lojista;
            this.senha_lojista = senha_lojista;
            this.cd_guia = cd_guia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retorna_dados_guiasResponse", WrapperNamespace="urn:server.retorna_dados_guias", IsWrapped=true)]
    public partial class retorna_dados_guiasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public retorna_dados_guiasResponse()
        {
        }
        
        public retorna_dados_guiasResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retorna_cidades", WrapperNamespace="urn:server.retorna_cidades", IsWrapped=true)]
    public partial class retorna_cidadesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string login_sistema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string senha_sistema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string cd_lojista;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string senha_lojista;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string cd_cidade;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string nm_cidade;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string uf;
        
        public retorna_cidadesRequest()
        {
        }
        
        public retorna_cidadesRequest(string login_sistema, string senha_sistema, string cd_lojista, string senha_lojista, string cd_cidade, string nm_cidade, string uf)
        {
            this.login_sistema = login_sistema;
            this.senha_sistema = senha_sistema;
            this.cd_lojista = cd_lojista;
            this.senha_lojista = senha_lojista;
            this.cd_cidade = cd_cidade;
            this.nm_cidade = nm_cidade;
            this.uf = uf;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retorna_cidadesResponse", WrapperNamespace="urn:server.retorna_cidades", IsWrapped=true)]
    public partial class retorna_cidadesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public retorna_cidadesResponse()
        {
        }
        
        public retorna_cidadesResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retorna_endereco_completo", WrapperNamespace="urn:server.retorna_endereco_completo", IsWrapped=true)]
    public partial class retorna_endereco_completoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string login_sistema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string senha_sistema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string cd_lojista;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string senha_lojista;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string nr_cep;
        
        public retorna_endereco_completoRequest()
        {
        }
        
        public retorna_endereco_completoRequest(string login_sistema, string senha_sistema, string cd_lojista, string senha_lojista, string nr_cep)
        {
            this.login_sistema = login_sistema;
            this.senha_sistema = senha_sistema;
            this.cd_lojista = cd_lojista;
            this.senha_lojista = senha_lojista;
            this.nr_cep = nr_cep;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retorna_endereco_completoResponse", WrapperNamespace="urn:server.retorna_endereco_completo", IsWrapped=true)]
    public partial class retorna_endereco_completoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public retorna_endereco_completoResponse()
        {
        }
        
        public retorna_endereco_completoResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retorna_tipos_pagamentos", WrapperNamespace="urn:server.retorna_tipos_pagamentos", IsWrapped=true)]
    public partial class retorna_tipos_pagamentosRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string login_sistema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string senha_sistema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string cd_lojista;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string senha_lojista;
        
        public retorna_tipos_pagamentosRequest()
        {
        }
        
        public retorna_tipos_pagamentosRequest(string login_sistema, string senha_sistema, string cd_lojista, string senha_lojista)
        {
            this.login_sistema = login_sistema;
            this.senha_sistema = senha_sistema;
            this.cd_lojista = cd_lojista;
            this.senha_lojista = senha_lojista;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retorna_tipos_pagamentosResponse", WrapperNamespace="urn:server.retorna_tipos_pagamentos", IsWrapped=true)]
    public partial class retorna_tipos_pagamentosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public retorna_tipos_pagamentosResponse()
        {
        }
        
        public retorna_tipos_pagamentosResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retorna_lojistas", WrapperNamespace="urn:server.retorna_lojistas", IsWrapped=true)]
    public partial class retorna_lojistasRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string login_sistema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string senha_sistema;
        
        public retorna_lojistasRequest()
        {
        }
        
        public retorna_lojistasRequest(string login_sistema, string senha_sistema)
        {
            this.login_sistema = login_sistema;
            this.senha_sistema = senha_sistema;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retorna_lojistasResponse", WrapperNamespace="urn:server.retorna_lojistas", IsWrapped=true)]
    public partial class retorna_lojistasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public retorna_lojistasResponse()
        {
        }
        
        public retorna_lojistasResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registra_cliente", WrapperNamespace="urn:server.registra_cliente", IsWrapped=true)]
    public partial class registra_clienteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string login_sistema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string senha_sistema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string cd_lojista;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string senha_lojista;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string pxml;
        
        public registra_clienteRequest()
        {
        }
        
        public registra_clienteRequest(string login_sistema, string senha_sistema, string cd_lojista, string senha_lojista, string pxml)
        {
            this.login_sistema = login_sistema;
            this.senha_sistema = senha_sistema;
            this.cd_lojista = cd_lojista;
            this.senha_lojista = senha_lojista;
            this.pxml = pxml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registra_clienteResponse", WrapperNamespace="urn:server.registra_cliente", IsWrapped=true)]
    public partial class registra_clienteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public registra_clienteResponse()
        {
        }
        
        public registra_clienteResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registra_venda_geral", WrapperNamespace="urn:server.registra_venda_cheque", IsWrapped=true)]
    public partial class registra_venda_geralRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string login_sistema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string senha_sistema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string cd_lojista;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string senha_lojista;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string cd_cartao_cliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string data_venda;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string cd_guia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string pxml;
        
        public registra_venda_geralRequest()
        {
        }
        
        public registra_venda_geralRequest(string login_sistema, string senha_sistema, string cd_lojista, string senha_lojista, string cd_cartao_cliente, string data_venda, string cd_guia, string pxml)
        {
            this.login_sistema = login_sistema;
            this.senha_sistema = senha_sistema;
            this.cd_lojista = cd_lojista;
            this.senha_lojista = senha_lojista;
            this.cd_cartao_cliente = cd_cartao_cliente;
            this.data_venda = data_venda;
            this.cd_guia = cd_guia;
            this.pxml = pxml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registra_venda_geralResponse", WrapperNamespace="urn:server.registra_venda_cheque", IsWrapped=true)]
    public partial class registra_venda_geralResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public registra_venda_geralResponse()
        {
        }
        
        public registra_venda_geralResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AdocaoLimites", WrapperNamespace="urn:server.AdocaoLimites", IsWrapped=true)]
    public partial class AdocaoLimitesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string senha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string Documento_Cliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string Nome_Origem;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string Codigo_Sistema_Gestao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public decimal Valor_Limite_Adotado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string Data_Validade;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string Nome_Classificacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public string Usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=9)]
        public string Nome_Politica_Cliente;
        
        public AdocaoLimitesRequest()
        {
        }
        
        public AdocaoLimitesRequest(string login, string senha, string Documento_Cliente, string Nome_Origem, string Codigo_Sistema_Gestao, decimal Valor_Limite_Adotado, string Data_Validade, string Nome_Classificacao, string Usuario, string Nome_Politica_Cliente)
        {
            this.login = login;
            this.senha = senha;
            this.Documento_Cliente = Documento_Cliente;
            this.Nome_Origem = Nome_Origem;
            this.Codigo_Sistema_Gestao = Codigo_Sistema_Gestao;
            this.Valor_Limite_Adotado = Valor_Limite_Adotado;
            this.Data_Validade = Data_Validade;
            this.Nome_Classificacao = Nome_Classificacao;
            this.Usuario = Usuario;
            this.Nome_Politica_Cliente = Nome_Politica_Cliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AdocaoLimitesResponse", WrapperNamespace="urn:server.AdocaoLimites", IsWrapped=true)]
    public partial class AdocaoLimitesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public AdocaoLimitesResponse()
        {
        }
        
        public AdocaoLimitesResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface serverSimplesTI_SMBPortTypeChannel : SimplesTI.serverSimplesTI_SMBPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class serverSimplesTI_SMBPortTypeClient : System.ServiceModel.ClientBase<SimplesTI.serverSimplesTI_SMBPortType>, SimplesTI.serverSimplesTI_SMBPortType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public serverSimplesTI_SMBPortTypeClient() : 
                base(serverSimplesTI_SMBPortTypeClient.GetDefaultBinding(), serverSimplesTI_SMBPortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.server_SimplesTI_SMBPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public serverSimplesTI_SMBPortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(serverSimplesTI_SMBPortTypeClient.GetBindingForEndpoint(endpointConfiguration), serverSimplesTI_SMBPortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public serverSimplesTI_SMBPortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(serverSimplesTI_SMBPortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public serverSimplesTI_SMBPortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(serverSimplesTI_SMBPortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public serverSimplesTI_SMBPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SimplesTI.testa_conexaoResponse> SimplesTI.serverSimplesTI_SMBPortType.testa_conexaoAsync(SimplesTI.testa_conexaoRequest request)
        {
            return base.Channel.testa_conexaoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SimplesTI.testa_conexaoResponse> testa_conexaoAsync(string login_sistema, string senha_sistema, string cd_lojista, string senha_lojista)
        {
            SimplesTI.testa_conexaoRequest inValue = new SimplesTI.testa_conexaoRequest();
            inValue.login_sistema = login_sistema;
            inValue.senha_sistema = senha_sistema;
            inValue.cd_lojista = cd_lojista;
            inValue.senha_lojista = senha_lojista;
            return ((SimplesTI.serverSimplesTI_SMBPortType)(this)).testa_conexaoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SimplesTI.retorna_dados_clientesResponse> SimplesTI.serverSimplesTI_SMBPortType.retorna_dados_clientesAsync(SimplesTI.retorna_dados_clientesRequest request)
        {
            return base.Channel.retorna_dados_clientesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SimplesTI.retorna_dados_clientesResponse> retorna_dados_clientesAsync(string login_sistema, string senha_sistema, string cd_lojista, string senha_lojista, string cd_cartao_cliente)
        {
            SimplesTI.retorna_dados_clientesRequest inValue = new SimplesTI.retorna_dados_clientesRequest();
            inValue.login_sistema = login_sistema;
            inValue.senha_sistema = senha_sistema;
            inValue.cd_lojista = cd_lojista;
            inValue.senha_lojista = senha_lojista;
            inValue.cd_cartao_cliente = cd_cartao_cliente;
            return ((SimplesTI.serverSimplesTI_SMBPortType)(this)).retorna_dados_clientesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SimplesTI.registra_venda_dinheiro_cartaoResponse> SimplesTI.serverSimplesTI_SMBPortType.registra_venda_dinheiro_cartaoAsync(SimplesTI.registra_venda_dinheiro_cartaoRequest request)
        {
            return base.Channel.registra_venda_dinheiro_cartaoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SimplesTI.registra_venda_dinheiro_cartaoResponse> registra_venda_dinheiro_cartaoAsync(string login_sistema, string senha_sistema, string cd_lojista, string senha_lojista, string cd_cartao_cliente, string tipo_pagamento, string data_venda, string qt_parcelas, string pparcelas_xml)
        {
            SimplesTI.registra_venda_dinheiro_cartaoRequest inValue = new SimplesTI.registra_venda_dinheiro_cartaoRequest();
            inValue.login_sistema = login_sistema;
            inValue.senha_sistema = senha_sistema;
            inValue.cd_lojista = cd_lojista;
            inValue.senha_lojista = senha_lojista;
            inValue.cd_cartao_cliente = cd_cartao_cliente;
            inValue.tipo_pagamento = tipo_pagamento;
            inValue.data_venda = data_venda;
            inValue.qt_parcelas = qt_parcelas;
            inValue.pparcelas_xml = pparcelas_xml;
            return ((SimplesTI.serverSimplesTI_SMBPortType)(this)).registra_venda_dinheiro_cartaoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SimplesTI.registra_venda_chequeResponse> SimplesTI.serverSimplesTI_SMBPortType.registra_venda_chequeAsync(SimplesTI.registra_venda_chequeRequest request)
        {
            return base.Channel.registra_venda_chequeAsync(request);
        }
        
        public System.Threading.Tasks.Task<SimplesTI.registra_venda_chequeResponse> registra_venda_chequeAsync(string login_sistema, string senha_sistema, string cd_lojista, string senha_lojista, string cd_cartao_cliente, string tipo_pagamento, string data_venda, string qt_cheques, string pcheques_xml)
        {
            SimplesTI.registra_venda_chequeRequest inValue = new SimplesTI.registra_venda_chequeRequest();
            inValue.login_sistema = login_sistema;
            inValue.senha_sistema = senha_sistema;
            inValue.cd_lojista = cd_lojista;
            inValue.senha_lojista = senha_lojista;
            inValue.cd_cartao_cliente = cd_cartao_cliente;
            inValue.tipo_pagamento = tipo_pagamento;
            inValue.data_venda = data_venda;
            inValue.qt_cheques = qt_cheques;
            inValue.pcheques_xml = pcheques_xml;
            return ((SimplesTI.serverSimplesTI_SMBPortType)(this)).registra_venda_chequeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SimplesTI.retorna_dados_guiasResponse> SimplesTI.serverSimplesTI_SMBPortType.retorna_dados_guiasAsync(SimplesTI.retorna_dados_guiasRequest request)
        {
            return base.Channel.retorna_dados_guiasAsync(request);
        }
        
        public System.Threading.Tasks.Task<SimplesTI.retorna_dados_guiasResponse> retorna_dados_guiasAsync(string login_sistema, string senha_sistema, string cd_lojista, string senha_lojista, string cd_guia)
        {
            SimplesTI.retorna_dados_guiasRequest inValue = new SimplesTI.retorna_dados_guiasRequest();
            inValue.login_sistema = login_sistema;
            inValue.senha_sistema = senha_sistema;
            inValue.cd_lojista = cd_lojista;
            inValue.senha_lojista = senha_lojista;
            inValue.cd_guia = cd_guia;
            return ((SimplesTI.serverSimplesTI_SMBPortType)(this)).retorna_dados_guiasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SimplesTI.retorna_cidadesResponse> SimplesTI.serverSimplesTI_SMBPortType.retorna_cidadesAsync(SimplesTI.retorna_cidadesRequest request)
        {
            return base.Channel.retorna_cidadesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SimplesTI.retorna_cidadesResponse> retorna_cidadesAsync(string login_sistema, string senha_sistema, string cd_lojista, string senha_lojista, string cd_cidade, string nm_cidade, string uf)
        {
            SimplesTI.retorna_cidadesRequest inValue = new SimplesTI.retorna_cidadesRequest();
            inValue.login_sistema = login_sistema;
            inValue.senha_sistema = senha_sistema;
            inValue.cd_lojista = cd_lojista;
            inValue.senha_lojista = senha_lojista;
            inValue.cd_cidade = cd_cidade;
            inValue.nm_cidade = nm_cidade;
            inValue.uf = uf;
            return ((SimplesTI.serverSimplesTI_SMBPortType)(this)).retorna_cidadesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SimplesTI.retorna_endereco_completoResponse> SimplesTI.serverSimplesTI_SMBPortType.retorna_endereco_completoAsync(SimplesTI.retorna_endereco_completoRequest request)
        {
            return base.Channel.retorna_endereco_completoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SimplesTI.retorna_endereco_completoResponse> retorna_endereco_completoAsync(string login_sistema, string senha_sistema, string cd_lojista, string senha_lojista, string nr_cep)
        {
            SimplesTI.retorna_endereco_completoRequest inValue = new SimplesTI.retorna_endereco_completoRequest();
            inValue.login_sistema = login_sistema;
            inValue.senha_sistema = senha_sistema;
            inValue.cd_lojista = cd_lojista;
            inValue.senha_lojista = senha_lojista;
            inValue.nr_cep = nr_cep;
            return ((SimplesTI.serverSimplesTI_SMBPortType)(this)).retorna_endereco_completoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SimplesTI.retorna_tipos_pagamentosResponse> SimplesTI.serverSimplesTI_SMBPortType.retorna_tipos_pagamentosAsync(SimplesTI.retorna_tipos_pagamentosRequest request)
        {
            return base.Channel.retorna_tipos_pagamentosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SimplesTI.retorna_tipos_pagamentosResponse> retorna_tipos_pagamentosAsync(string login_sistema, string senha_sistema, string cd_lojista, string senha_lojista)
        {
            SimplesTI.retorna_tipos_pagamentosRequest inValue = new SimplesTI.retorna_tipos_pagamentosRequest();
            inValue.login_sistema = login_sistema;
            inValue.senha_sistema = senha_sistema;
            inValue.cd_lojista = cd_lojista;
            inValue.senha_lojista = senha_lojista;
            return ((SimplesTI.serverSimplesTI_SMBPortType)(this)).retorna_tipos_pagamentosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SimplesTI.retorna_lojistasResponse> SimplesTI.serverSimplesTI_SMBPortType.retorna_lojistasAsync(SimplesTI.retorna_lojistasRequest request)
        {
            return base.Channel.retorna_lojistasAsync(request);
        }
        
        public System.Threading.Tasks.Task<SimplesTI.retorna_lojistasResponse> retorna_lojistasAsync(string login_sistema, string senha_sistema)
        {
            SimplesTI.retorna_lojistasRequest inValue = new SimplesTI.retorna_lojistasRequest();
            inValue.login_sistema = login_sistema;
            inValue.senha_sistema = senha_sistema;
            return ((SimplesTI.serverSimplesTI_SMBPortType)(this)).retorna_lojistasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SimplesTI.registra_clienteResponse> SimplesTI.serverSimplesTI_SMBPortType.registra_clienteAsync(SimplesTI.registra_clienteRequest request)
        {
            return base.Channel.registra_clienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<SimplesTI.registra_clienteResponse> registra_clienteAsync(string login_sistema, string senha_sistema, string cd_lojista, string senha_lojista, string pxml)
        {
            SimplesTI.registra_clienteRequest inValue = new SimplesTI.registra_clienteRequest();
            inValue.login_sistema = login_sistema;
            inValue.senha_sistema = senha_sistema;
            inValue.cd_lojista = cd_lojista;
            inValue.senha_lojista = senha_lojista;
            inValue.pxml = pxml;
            return ((SimplesTI.serverSimplesTI_SMBPortType)(this)).registra_clienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SimplesTI.registra_venda_geralResponse> SimplesTI.serverSimplesTI_SMBPortType.registra_venda_geralAsync(SimplesTI.registra_venda_geralRequest request)
        {
            return base.Channel.registra_venda_geralAsync(request);
        }
        
        public System.Threading.Tasks.Task<SimplesTI.registra_venda_geralResponse> registra_venda_geralAsync(string login_sistema, string senha_sistema, string cd_lojista, string senha_lojista, string cd_cartao_cliente, string data_venda, string cd_guia, string pxml)
        {
            SimplesTI.registra_venda_geralRequest inValue = new SimplesTI.registra_venda_geralRequest();
            inValue.login_sistema = login_sistema;
            inValue.senha_sistema = senha_sistema;
            inValue.cd_lojista = cd_lojista;
            inValue.senha_lojista = senha_lojista;
            inValue.cd_cartao_cliente = cd_cartao_cliente;
            inValue.data_venda = data_venda;
            inValue.cd_guia = cd_guia;
            inValue.pxml = pxml;
            return ((SimplesTI.serverSimplesTI_SMBPortType)(this)).registra_venda_geralAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SimplesTI.AdocaoLimitesResponse> SimplesTI.serverSimplesTI_SMBPortType.AdocaoLimitesAsync(SimplesTI.AdocaoLimitesRequest request)
        {
            return base.Channel.AdocaoLimitesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SimplesTI.AdocaoLimitesResponse> AdocaoLimitesAsync(string login, string senha, string Documento_Cliente, string Nome_Origem, string Codigo_Sistema_Gestao, decimal Valor_Limite_Adotado, string Data_Validade, string Nome_Classificacao, string Usuario, string Nome_Politica_Cliente)
        {
            SimplesTI.AdocaoLimitesRequest inValue = new SimplesTI.AdocaoLimitesRequest();
            inValue.login = login;
            inValue.senha = senha;
            inValue.Documento_Cliente = Documento_Cliente;
            inValue.Nome_Origem = Nome_Origem;
            inValue.Codigo_Sistema_Gestao = Codigo_Sistema_Gestao;
            inValue.Valor_Limite_Adotado = Valor_Limite_Adotado;
            inValue.Data_Validade = Data_Validade;
            inValue.Nome_Classificacao = Nome_Classificacao;
            inValue.Usuario = Usuario;
            inValue.Nome_Politica_Cliente = Nome_Politica_Cliente;
            return ((SimplesTI.serverSimplesTI_SMBPortType)(this)).AdocaoLimitesAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.server_SimplesTI_SMBPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.server_SimplesTI_SMBPort))
            {
                return new System.ServiceModel.EndpointAddress("http://200.185.223.230:9935/WSNetX/server.php");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return serverSimplesTI_SMBPortTypeClient.GetBindingForEndpoint(EndpointConfiguration.server_SimplesTI_SMBPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return serverSimplesTI_SMBPortTypeClient.GetEndpointAddress(EndpointConfiguration.server_SimplesTI_SMBPort);
        }
        
        public enum EndpointConfiguration
        {
            
            server_SimplesTI_SMBPort,
        }
    }
}
